/* nh_globals.c -- per-environment context storage and initialisation.
 * GENERATED by tools/collect_globals -- do not edit by hand. */

#include "hack.h"

NH_THREAD_LOCAL struct nh_globals *nh_g;

/* The .data image of every initialized object: `const` templates left at
 * the original definition sites. Weak, so a program that links only a
 * few game files (lev_comp) simply skips the templates it lacks. */
extern const char *const nh_tmpl_Izchak_speaks[9] __attribute__((weak));
extern const winid nh_tmpl_WIN_INVEN __attribute__((weak));
extern const winid nh_tmpl_WIN_MAP __attribute__((weak));
extern const winid nh_tmpl_WIN_MESSAGE __attribute__((weak));
extern const winid nh_tmpl_WIN_STATUS __attribute__((weak));
extern const char *const nh_tmpl_beats[8] __attribute__((weak));
extern const char nh_tmpl_bones[12] __attribute__((weak));
extern const char *const nh_tmpl_bottlenames[7] __attribute__((weak));
extern const struct c_color_names nh_tmpl_c_color_names __attribute__((weak));
extern const struct c_common_strings nh_tmpl_c_common_strings __attribute__((weak));
extern const char *const nh_tmpl_c_obj_colors[16] __attribute__((weak));
extern const char nh_tmpl_circle_data[136] __attribute__((weak));
extern const char nh_tmpl_circle_start[16] __attribute__((weak));
extern const char *const nh_tmpl_default_configfile __attribute__((weak));
extern const char nh_tmpl_defmorestr[9] __attribute__((weak));
extern const dest_area nh_tmpl_dndest __attribute__((weak));
extern const stairway nh_tmpl_dnladder __attribute__((weak));
extern const stairway nh_tmpl_dnstair __attribute__((weak));
extern const coord nh_tmpl_doors[DOORMAX] __attribute__((weak));
extern const struct dgn_topology nh_tmpl_dungeon_topology __attribute__((weak));
extern const struct ext_func_tab nh_tmpl_extcmdlist[113] __attribute__((weak));
extern char *const nh_tmpl_fqn_prefix[PREFIX_COUNT] __attribute__((weak));
extern const char *const nh_tmpl_fqn_prefix_names[PREFIX_COUNT] __attribute__((weak));
extern const char *const nh_tmpl_hu_stat[7] __attribute__((weak));
extern const coord nh_tmpl_inv_pos __attribute__((weak));
extern const char *const nh_tmpl_known_handling[6] __attribute__((weak));
extern const char *const nh_tmpl_known_restrictions[3] __attribute__((weak));
extern const char *const nh_tmpl_l_botl_c_parse_status_hl2_aligntxt[3] __attribute__((weak));
extern const char *const nh_tmpl_l_botl_c_parse_status_hl2_hutxt[7] __attribute__((weak));
extern const char *const nh_tmpl_l_botl_c_status_hilite_menu_add_aligntxt[3] __attribute__((weak));
extern const char *const nh_tmpl_l_botl_c_status_hilite_menu_add_hutxt[7] __attribute__((weak));
extern const char nh_tmpl_l_cmd_c_basics_enlightenment_Power[28] __attribute__((weak));
extern const char nh_tmpl_l_files_c_fname_decode_hexdigits[17] __attribute__((weak));
extern const char nh_tmpl_l_files_c_fname_encode_hexdigits[17] __attribute__((weak));
extern const unsigned int nh_tmpl_l_hack_c_spoteffects_spottraptyp __attribute__((weak));
extern const char nh_tmpl_l_invent_c_loot_classify_def_srt_order[MAXOCLASSES] __attribute__((weak));
extern const char nh_tmpl_l_lock_c_pick_lock_no_longer[40] __attribute__((weak));
extern const char nh_tmpl_l_options_c_parseoptions_gpcoords[6] __attribute__((weak));
extern const char nh_tmpl_l_options_c_parseoptions_valid_settings[7] __attribute__((weak));
extern const int nh_tmpl_l_pickup_c_encumber_msg_oldcap __attribute__((weak));
extern const char nh_tmpl_l_role_c_root_plselection_prompt_err_ret[13] __attribute__((weak));
extern const short nh_tmpl_l_u_init_c_ini_inv_nocreate __attribute__((weak));
extern const short nh_tmpl_l_u_init_c_ini_inv_nocreate2 __attribute__((weak));
extern const short nh_tmpl_l_u_init_c_ini_inv_nocreate3 __attribute__((weak));
extern const short nh_tmpl_l_u_init_c_ini_inv_nocreate4 __attribute__((weak));
extern const enum statusfields nh_tmpl_l_windows_c_genl_status_update_fieldorder[5][15] __attribute__((weak));
extern const schar nh_tmpl_lastseentyp[COLNO][ROWNO] __attribute__((weak));
extern const struct symparse nh_tmpl_loadsyms[186] __attribute__((weak));
extern const char nh_tmpl_lock[PL_NSIZ+14] __attribute__((weak));
extern const struct multishot nh_tmpl_m_shot __attribute__((weak));
extern const char *const nh_tmpl_materialnm[22] __attribute__((weak));
extern const struct permonst nh_tmpl_mons[382] __attribute__((weak));
extern const long nh_tmpl_monstermoves __attribute__((weak));
extern const long nh_tmpl_moves __attribute__((weak));
extern const unsigned long nh_tmpl_nle_seeds[2] __attribute__((weak));
extern const struct objdescr nh_tmpl_obj_descr[454] __attribute__((weak));
extern const struct objclass nh_tmpl_objects[454] __attribute__((weak));
extern const struct mkroom nh_tmpl_rooms[(MAXNROFROOMS+1)*2] __attribute__((weak));
extern const int nh_tmpl_s_apply_c_polearm_range_max __attribute__((weak));
extern const int nh_tmpl_s_apply_c_polearm_range_min __attribute__((weak));
extern const struct artifact nh_tmpl_s_artilist_h_artilist[35] __attribute__((weak));
extern const struct innate nh_tmpl_s_attrib_c_hum_abil[1] __attribute__((weak));
extern const winid nh_tmpl_s_cmd_c_en_win __attribute__((weak));
extern const char *const nh_tmpl_s_cmd_c_readchar_queue __attribute__((weak));
extern boolean (*const nh_tmpl_s_do_name_c_getpos_getvalid)(int, int) __attribute__((weak));
extern void (*const nh_tmpl_s_do_name_c_getpos_hilitefunc)(int) __attribute__((weak));
extern const int nh_tmpl_s_end_c_vanq_sortmode __attribute__((weak));
extern const int nh_tmpl_s_files_c_lockfd __attribute__((weak));
extern const winid nh_tmpl_s_invent_c_cached_pickinv_win __attribute__((weak));
extern const int nh_tmpl_s_invent_c_lastinvnr __attribute__((weak));
extern const char nh_tmpl_s_invent_c_venom_inv[2] __attribute__((weak));
extern const struct nh_anon_s_makemon_c_rndmonst_state nh_tmpl_s_makemon_c_rndmonst_state __attribute__((weak));
extern const struct Jitem nh_tmpl_s_objnam_c_Japanese_items[13] __attribute__((weak));
extern const struct sing_plur nh_tmpl_s_objnam_c_one_off[22] __attribute__((weak));
extern const char nh_tmpl_s_options_c_def_inv_order[MAXOCLASSES] __attribute__((weak));
extern const char nh_tmpl_s_options_c_empty_optstr[1] __attribute__((weak));
extern const char nh_tmpl_s_options_c_fmtstr_doset[16] __attribute__((weak));
extern const char nh_tmpl_s_options_c_fmtstr_doset_tab[8] __attribute__((weak));
extern const char nh_tmpl_s_options_c_n_currently_set[19] __attribute__((weak));
extern const char *const nh_tmpl_s_options_c_opt_intro[10] __attribute__((weak));
extern const char *const nh_tmpl_s_pager_c_suptext1[9] __attribute__((weak));
extern const char *const nh_tmpl_s_pager_c_suptext2[7] __attribute__((weak));
extern const struct restore_procs nh_tmpl_s_restore_c_restoreprocs __attribute__((weak));
extern const struct rnglist_t nh_tmpl_s_rnd_c_rnglist[2] __attribute__((weak));
extern const char nh_tmpl_s_role_c_randomstr[7] __attribute__((weak));
extern const int nh_tmpl_s_save_c_bw_fd __attribute__((weak));
extern const struct save_procs nh_tmpl_s_save_c_saveprocs __attribute__((weak));
extern const int nh_tmpl_s_shk_c_sell_how __attribute__((weak));
extern const char nh_tmpl_s_shk_c_sell_response __attribute__((weak));
extern const aligntyp nh_tmpl_s_sp_lev_c_ralign[3] __attribute__((weak));
extern const char nh_tmpl_s_termcap_c_adef_nilstring[1] __attribute__((weak));
extern const char nh_tmpl_s_termcap_c_nullstr[1] __attribute__((weak));
extern const char nh_tmpl_s_termcap_c_nulstr[1] __attribute__((weak));
extern const unsigned long nh_tmpl_s_timeout_c_timer_id __attribute__((weak));
extern const winid nh_tmpl_s_topten_c_toptenwin __attribute__((weak));
extern const struct h2o_ctx nh_tmpl_s_trap_c_acid_ctx __attribute__((weak));
extern const struct trobj nh_tmpl_s_u_init_c_Archeologist[9] __attribute__((weak));
extern const struct trobj nh_tmpl_s_u_init_c_Barbarian[5] __attribute__((weak));
extern const struct trobj nh_tmpl_s_u_init_c_Blindfold[2] __attribute__((weak));
extern const struct trobj nh_tmpl_s_u_init_c_Cave_man[6] __attribute__((weak));
extern const struct trobj nh_tmpl_s_u_init_c_Healer[11] __attribute__((weak));
extern const struct trobj nh_tmpl_s_u_init_c_Instrument[2] __attribute__((weak));
extern const struct trobj nh_tmpl_s_u_init_c_Knight[9] __attribute__((weak));
extern const struct trobj nh_tmpl_s_u_init_c_Lamp[2] __attribute__((weak));
extern const struct trobj nh_tmpl_s_u_init_c_Leash[2] __attribute__((weak));
extern const struct trobj nh_tmpl_s_u_init_c_Magicmarker[2] __attribute__((weak));
extern const struct trobj nh_tmpl_s_u_init_c_Money[2] __attribute__((weak));
extern const struct trobj nh_tmpl_s_u_init_c_Monk[10] __attribute__((weak));
extern const struct trobj nh_tmpl_s_u_init_c_Priest[8] __attribute__((weak));
extern const struct trobj nh_tmpl_s_u_init_c_Ranger[7] __attribute__((weak));
extern const struct trobj nh_tmpl_s_u_init_c_Rogue[7] __attribute__((weak));
extern const struct trobj nh_tmpl_s_u_init_c_Samurai[6] __attribute__((weak));
extern const struct trobj nh_tmpl_s_u_init_c_Tinopener[2] __attribute__((weak));
extern const struct trobj nh_tmpl_s_u_init_c_Tourist[8] __attribute__((weak));
extern const struct trobj nh_tmpl_s_u_init_c_Towel[2] __attribute__((weak));
extern const struct trobj nh_tmpl_s_u_init_c_Valkyrie[5] __attribute__((weak));
extern const struct trobj nh_tmpl_s_u_init_c_Wishing[2] __attribute__((weak));
extern const struct trobj nh_tmpl_s_u_init_c_Wizard[9] __attribute__((weak));
extern const struct trobj nh_tmpl_s_u_init_c_Xtra_food[2] __attribute__((weak));
extern const char nh_tmpl_s_wintty_c_winpanicstr[17] __attribute__((weak));
extern const d_level nh_tmpl_save_dlevel __attribute__((weak));
extern const unsigned char nh_tmpl_seenv_matrix[3][3] __attribute__((weak));
extern const struct savefile_info nh_tmpl_sfcap __attribute__((weak));
extern const struct savefile_info nh_tmpl_sfsaveinfo __attribute__((weak));
extern const struct spell nh_tmpl_spl_book[MAXSPELL+1] __attribute__((weak));
extern const stairway nh_tmpl_sstairs __attribute__((weak));
extern const struct tc_gbl_data nh_tmpl_tc_gbl_data __attribute__((weak));
extern const struct tc_lcl_data nh_tmpl_tc_lcl_data __attribute__((weak));
extern const struct window_procs nh_tmpl_tty_procs __attribute__((weak));
extern const dest_area nh_tmpl_updest __attribute__((weak));
extern const stairway nh_tmpl_upladder __attribute__((weak));
extern const stairway nh_tmpl_upstair __attribute__((weak));
extern const struct Race nh_tmpl_urace __attribute__((weak));
extern const struct Role nh_tmpl_urole __attribute__((weak));
extern const int nh_tmpl_x_maze_max __attribute__((weak));
extern const int nh_tmpl_y_maze_max __attribute__((weak));

size_t
nh_globals_size(void)
{
    return sizeof(struct nh_globals);
}

void
nh_globals_init(struct nh_globals *g)
{
    memset((genericptr_t) g, 0, sizeof *g);
    nh_g = g;
    if (&nh_tmpl_s_apply_c_polearm_range_min)
        memcpy(&(nh_g->s_apply_c_polearm_range_min), &nh_tmpl_s_apply_c_polearm_range_min, sizeof (nh_g->s_apply_c_polearm_range_min));
    if (&nh_tmpl_s_apply_c_polearm_range_max)
        memcpy(&(nh_g->s_apply_c_polearm_range_max), &nh_tmpl_s_apply_c_polearm_range_max, sizeof (nh_g->s_apply_c_polearm_range_max));
    if (&nh_tmpl_s_artilist_h_artilist)
        memcpy(&(nh_g->s_artilist_h_artilist), &nh_tmpl_s_artilist_h_artilist, sizeof (nh_g->s_artilist_h_artilist));
    if (&nh_tmpl_s_attrib_c_hum_abil)
        memcpy(&(nh_g->s_attrib_c_hum_abil), &nh_tmpl_s_attrib_c_hum_abil, sizeof (nh_g->s_attrib_c_hum_abil));
    if (&nh_tmpl_l_botl_c_parse_status_hl2_aligntxt)
        memcpy(&(nh_g->l_botl_c_parse_status_hl2_aligntxt), &nh_tmpl_l_botl_c_parse_status_hl2_aligntxt, sizeof (nh_g->l_botl_c_parse_status_hl2_aligntxt));
    if (&nh_tmpl_l_botl_c_parse_status_hl2_hutxt)
        memcpy(&(nh_g->l_botl_c_parse_status_hl2_hutxt), &nh_tmpl_l_botl_c_parse_status_hl2_hutxt, sizeof (nh_g->l_botl_c_parse_status_hl2_hutxt));
    if (&nh_tmpl_l_botl_c_status_hilite_menu_add_aligntxt)
        memcpy(&(nh_g->l_botl_c_status_hilite_menu_add_aligntxt), &nh_tmpl_l_botl_c_status_hilite_menu_add_aligntxt, sizeof (nh_g->l_botl_c_status_hilite_menu_add_aligntxt));
    if (&nh_tmpl_l_botl_c_status_hilite_menu_add_hutxt)
        memcpy(&(nh_g->l_botl_c_status_hilite_menu_add_hutxt), &nh_tmpl_l_botl_c_status_hilite_menu_add_hutxt, sizeof (nh_g->l_botl_c_status_hilite_menu_add_hutxt));
    if (&nh_tmpl_s_cmd_c_readchar_queue)
        memcpy(&(nh_g->s_cmd_c_readchar_queue), &nh_tmpl_s_cmd_c_readchar_queue, sizeof (nh_g->s_cmd_c_readchar_queue));
    if (&nh_tmpl_s_cmd_c_en_win)
        memcpy(&(nh_g->s_cmd_c_en_win), &nh_tmpl_s_cmd_c_en_win, sizeof (nh_g->s_cmd_c_en_win));
    if (&nh_tmpl_l_cmd_c_basics_enlightenment_Power)
        memcpy(&(nh_g->l_cmd_c_basics_enlightenment_Power), &nh_tmpl_l_cmd_c_basics_enlightenment_Power, sizeof (nh_g->l_cmd_c_basics_enlightenment_Power));
    if (&nh_tmpl_extcmdlist)
        memcpy(&extcmdlist, &nh_tmpl_extcmdlist, sizeof extcmdlist);
    if (&nh_tmpl_x_maze_max)
        memcpy(&x_maze_max, &nh_tmpl_x_maze_max, sizeof x_maze_max);
    if (&nh_tmpl_y_maze_max)
        memcpy(&y_maze_max, &nh_tmpl_y_maze_max, sizeof y_maze_max);
    if (&nh_tmpl_dungeon_topology)
        memcpy(&dungeon_topology, &nh_tmpl_dungeon_topology, sizeof dungeon_topology);
    if (&nh_tmpl_m_shot)
        memcpy(&m_shot, &nh_tmpl_m_shot, sizeof m_shot);
    if (&nh_tmpl_upstair)
        memcpy(&upstair, &nh_tmpl_upstair, sizeof upstair);
    if (&nh_tmpl_dnstair)
        memcpy(&dnstair, &nh_tmpl_dnstair, sizeof dnstair);
    if (&nh_tmpl_upladder)
        memcpy(&upladder, &nh_tmpl_upladder, sizeof upladder);
    if (&nh_tmpl_dnladder)
        memcpy(&dnladder, &nh_tmpl_dnladder, sizeof dnladder);
    if (&nh_tmpl_sstairs)
        memcpy(&sstairs, &nh_tmpl_sstairs, sizeof sstairs);
    if (&nh_tmpl_updest)
        memcpy(&updest, &nh_tmpl_updest, sizeof updest);
    if (&nh_tmpl_dndest)
        memcpy(&dndest, &nh_tmpl_dndest, sizeof dndest);
    if (&nh_tmpl_inv_pos)
        memcpy(&inv_pos, &nh_tmpl_inv_pos, sizeof inv_pos);
    if (&nh_tmpl_doors)
        memcpy(&doors, &nh_tmpl_doors, sizeof doors);
    if (&nh_tmpl_rooms)
        memcpy(&rooms, &nh_tmpl_rooms, sizeof rooms);
    if (&nh_tmpl_lastseentyp)
        memcpy(&lastseentyp, &nh_tmpl_lastseentyp, sizeof lastseentyp);
    if (&nh_tmpl_spl_book)
        memcpy(&spl_book, &nh_tmpl_spl_book, sizeof spl_book);
    if (&nh_tmpl_moves)
        memcpy(&moves, &nh_tmpl_moves, sizeof moves);
    if (&nh_tmpl_monstermoves)
        memcpy(&monstermoves, &nh_tmpl_monstermoves, sizeof monstermoves);
    if (&nh_tmpl_c_color_names)
        memcpy(&(nh_g->c_color_names), &nh_tmpl_c_color_names, sizeof (nh_g->c_color_names));
    if (&nh_tmpl_c_obj_colors)
        memcpy(&c_obj_colors, &nh_tmpl_c_obj_colors, sizeof c_obj_colors);
    if (&nh_tmpl_c_common_strings)
        memcpy(&(nh_g->c_common_strings), &nh_tmpl_c_common_strings, sizeof (nh_g->c_common_strings));
    if (&nh_tmpl_materialnm)
        memcpy(&materialnm, &nh_tmpl_materialnm, sizeof materialnm);
    if (&nh_tmpl_WIN_MESSAGE)
        memcpy(&WIN_MESSAGE, &nh_tmpl_WIN_MESSAGE, sizeof WIN_MESSAGE);
    if (&nh_tmpl_WIN_STATUS)
        memcpy(&WIN_STATUS, &nh_tmpl_WIN_STATUS, sizeof WIN_STATUS);
    if (&nh_tmpl_WIN_MAP)
        memcpy(&WIN_MAP, &nh_tmpl_WIN_MAP, sizeof WIN_MAP);
    if (&nh_tmpl_WIN_INVEN)
        memcpy(&WIN_INVEN, &nh_tmpl_WIN_INVEN, sizeof WIN_INVEN);
    if (&nh_tmpl_tc_gbl_data)
        memcpy(&(nh_g->tc_gbl_data), &nh_tmpl_tc_gbl_data, sizeof (nh_g->tc_gbl_data));
    if (&nh_tmpl_fqn_prefix)
        memcpy(&fqn_prefix, &nh_tmpl_fqn_prefix, sizeof fqn_prefix);
    if (&nh_tmpl_fqn_prefix_names)
        memcpy(&fqn_prefix_names, &nh_tmpl_fqn_prefix_names, sizeof fqn_prefix_names);
    if (&nh_tmpl_sfcap)
        memcpy(&sfcap, &nh_tmpl_sfcap, sizeof sfcap);
    if (&nh_tmpl_sfsaveinfo)
        memcpy(&sfsaveinfo, &nh_tmpl_sfsaveinfo, sizeof sfsaveinfo);
    if (&nh_tmpl_seenv_matrix)
        memcpy(&seenv_matrix, &nh_tmpl_seenv_matrix, sizeof seenv_matrix);
    if (&nh_tmpl_save_dlevel)
        memcpy(&save_dlevel, &nh_tmpl_save_dlevel, sizeof save_dlevel);
    if (&nh_tmpl_s_do_name_c_getpos_hilitefunc)
        memcpy(&(nh_g->s_do_name_c_getpos_hilitefunc), &nh_tmpl_s_do_name_c_getpos_hilitefunc, sizeof (nh_g->s_do_name_c_getpos_hilitefunc));
    if (&nh_tmpl_s_do_name_c_getpos_getvalid)
        memcpy(&(nh_g->s_do_name_c_getpos_getvalid), &nh_tmpl_s_do_name_c_getpos_getvalid, sizeof (nh_g->s_do_name_c_getpos_getvalid));
    if (&nh_tmpl_known_handling)
        memcpy(&known_handling, &nh_tmpl_known_handling, sizeof known_handling);
    if (&nh_tmpl_known_restrictions)
        memcpy(&known_restrictions, &nh_tmpl_known_restrictions, sizeof known_restrictions);
    if (&nh_tmpl_loadsyms)
        memcpy(&loadsyms, &nh_tmpl_loadsyms, sizeof loadsyms);
    if (&nh_tmpl_hu_stat)
        memcpy(&hu_stat, &nh_tmpl_hu_stat, sizeof hu_stat);
    if (&nh_tmpl_s_end_c_vanq_sortmode)
        memcpy(&(nh_g->s_end_c_vanq_sortmode), &nh_tmpl_s_end_c_vanq_sortmode, sizeof (nh_g->s_end_c_vanq_sortmode));
    if (&nh_tmpl_bones)
        memcpy(&(nh_g->bones), &nh_tmpl_bones, sizeof (nh_g->bones));
    if (&nh_tmpl_lock)
        memcpy(&lock, &nh_tmpl_lock, sizeof lock);
    if (&nh_tmpl_l_files_c_fname_encode_hexdigits)
        memcpy(&(nh_g->l_files_c_fname_encode_hexdigits), &nh_tmpl_l_files_c_fname_encode_hexdigits, sizeof (nh_g->l_files_c_fname_encode_hexdigits));
    if (&nh_tmpl_l_files_c_fname_decode_hexdigits)
        memcpy(&(nh_g->l_files_c_fname_decode_hexdigits), &nh_tmpl_l_files_c_fname_decode_hexdigits, sizeof (nh_g->l_files_c_fname_decode_hexdigits));
    if (&nh_tmpl_s_files_c_lockfd)
        memcpy(&(nh_g->s_files_c_lockfd), &nh_tmpl_s_files_c_lockfd, sizeof (nh_g->s_files_c_lockfd));
    if (&nh_tmpl_default_configfile)
        memcpy(&default_configfile, &nh_tmpl_default_configfile, sizeof default_configfile);
    if (&nh_tmpl_l_hack_c_spoteffects_spottraptyp)
        memcpy(&(nh_g->l_hack_c_spoteffects_spottraptyp), &nh_tmpl_l_hack_c_spoteffects_spottraptyp, sizeof (nh_g->l_hack_c_spoteffects_spottraptyp));
    if (&nh_tmpl_nle_seeds)
        memcpy(&nle_seeds, &nh_tmpl_nle_seeds, sizeof nle_seeds);
    if (&nh_tmpl_s_invent_c_lastinvnr)
        memcpy(&(nh_g->s_invent_c_lastinvnr), &nh_tmpl_s_invent_c_lastinvnr, sizeof (nh_g->s_invent_c_lastinvnr));
    if (&nh_tmpl_s_invent_c_venom_inv)
        memcpy(&(nh_g->s_invent_c_venom_inv), &nh_tmpl_s_invent_c_venom_inv, sizeof (nh_g->s_invent_c_venom_inv));
    if (&nh_tmpl_l_invent_c_loot_classify_def_srt_order)
        memcpy(&(nh_g->l_invent_c_loot_classify_def_srt_order), &nh_tmpl_l_invent_c_loot_classify_def_srt_order, sizeof (nh_g->l_invent_c_loot_classify_def_srt_order));
    if (&nh_tmpl_s_invent_c_cached_pickinv_win)
        memcpy(&(nh_g->s_invent_c_cached_pickinv_win), &nh_tmpl_s_invent_c_cached_pickinv_win, sizeof (nh_g->s_invent_c_cached_pickinv_win));
    if (&nh_tmpl_l_lock_c_pick_lock_no_longer)
        memcpy(&(nh_g->l_lock_c_pick_lock_no_longer), &nh_tmpl_l_lock_c_pick_lock_no_longer, sizeof (nh_g->l_lock_c_pick_lock_no_longer));
    if (&nh_tmpl_s_makemon_c_rndmonst_state)
        memcpy(&(nh_g->s_makemon_c_rndmonst_state), &nh_tmpl_s_makemon_c_rndmonst_state, sizeof (nh_g->s_makemon_c_rndmonst_state));
    if (&nh_tmpl_mons)
        memcpy(&mons, &nh_tmpl_mons, sizeof mons);
    if (&nh_tmpl_beats)
        memcpy(&beats, &nh_tmpl_beats, sizeof beats);
    if (&nh_tmpl_obj_descr)
        memcpy(&obj_descr, &nh_tmpl_obj_descr, sizeof obj_descr);
    if (&nh_tmpl_objects)
        memcpy(&(nh_g->objects), &nh_tmpl_objects, sizeof (nh_g->objects));
    if (&nh_tmpl_s_objnam_c_Japanese_items)
        memcpy(&(nh_g->s_objnam_c_Japanese_items), &nh_tmpl_s_objnam_c_Japanese_items, sizeof (nh_g->s_objnam_c_Japanese_items));
    if (&nh_tmpl_s_objnam_c_one_off)
        memcpy(&(nh_g->s_objnam_c_one_off), &nh_tmpl_s_objnam_c_one_off, sizeof (nh_g->s_objnam_c_one_off));
    if (&nh_tmpl_s_options_c_empty_optstr)
        memcpy(&(nh_g->s_options_c_empty_optstr), &nh_tmpl_s_options_c_empty_optstr, sizeof (nh_g->s_options_c_empty_optstr));
    if (&nh_tmpl_s_options_c_def_inv_order)
        memcpy(&(nh_g->s_options_c_def_inv_order), &nh_tmpl_s_options_c_def_inv_order, sizeof (nh_g->s_options_c_def_inv_order));
    if (&nh_tmpl_l_options_c_parseoptions_gpcoords)
        memcpy(&(nh_g->l_options_c_parseoptions_gpcoords), &nh_tmpl_l_options_c_parseoptions_gpcoords, sizeof (nh_g->l_options_c_parseoptions_gpcoords));
    if (&nh_tmpl_l_options_c_parseoptions_valid_settings)
        memcpy(&(nh_g->l_options_c_parseoptions_valid_settings), &nh_tmpl_l_options_c_parseoptions_valid_settings, sizeof (nh_g->l_options_c_parseoptions_valid_settings));
    if (&nh_tmpl_s_options_c_fmtstr_doset)
        memcpy(&(nh_g->s_options_c_fmtstr_doset), &nh_tmpl_s_options_c_fmtstr_doset, sizeof (nh_g->s_options_c_fmtstr_doset));
    if (&nh_tmpl_s_options_c_fmtstr_doset_tab)
        memcpy(&(nh_g->s_options_c_fmtstr_doset_tab), &nh_tmpl_s_options_c_fmtstr_doset_tab, sizeof (nh_g->s_options_c_fmtstr_doset_tab));
    if (&nh_tmpl_s_options_c_n_currently_set)
        memcpy(&(nh_g->s_options_c_n_currently_set), &nh_tmpl_s_options_c_n_currently_set, sizeof (nh_g->s_options_c_n_currently_set));
    if (&nh_tmpl_s_options_c_opt_intro)
        memcpy(&(nh_g->s_options_c_opt_intro), &nh_tmpl_s_options_c_opt_intro, sizeof (nh_g->s_options_c_opt_intro));
    if (&nh_tmpl_s_pager_c_suptext1)
        memcpy(&(nh_g->s_pager_c_suptext1), &nh_tmpl_s_pager_c_suptext1, sizeof (nh_g->s_pager_c_suptext1));
    if (&nh_tmpl_s_pager_c_suptext2)
        memcpy(&(nh_g->s_pager_c_suptext2), &nh_tmpl_s_pager_c_suptext2, sizeof (nh_g->s_pager_c_suptext2));
    if (&nh_tmpl_l_pickup_c_encumber_msg_oldcap)
        memcpy(&(nh_g->l_pickup_c_encumber_msg_oldcap), &nh_tmpl_l_pickup_c_encumber_msg_oldcap, sizeof (nh_g->l_pickup_c_encumber_msg_oldcap));
    if (&nh_tmpl_bottlenames)
        memcpy(&bottlenames, &nh_tmpl_bottlenames, sizeof bottlenames);
    if (&nh_tmpl_s_restore_c_restoreprocs)
        memcpy(&(nh_g->s_restore_c_restoreprocs), &nh_tmpl_s_restore_c_restoreprocs, sizeof (nh_g->s_restore_c_restoreprocs));
    if (&nh_tmpl_s_rnd_c_rnglist)
        memcpy(&(nh_g->s_rnd_c_rnglist), &nh_tmpl_s_rnd_c_rnglist, sizeof (nh_g->s_rnd_c_rnglist));
    if (&nh_tmpl_urole)
        memcpy(&urole, &nh_tmpl_urole, sizeof urole);
    if (&nh_tmpl_urace)
        memcpy(&urace, &nh_tmpl_urace, sizeof urace);
    if (&nh_tmpl_s_role_c_randomstr)
        memcpy(&(nh_g->s_role_c_randomstr), &nh_tmpl_s_role_c_randomstr, sizeof (nh_g->s_role_c_randomstr));
    if (&nh_tmpl_l_role_c_root_plselection_prompt_err_ret)
        memcpy(&(nh_g->l_role_c_root_plselection_prompt_err_ret), &nh_tmpl_l_role_c_root_plselection_prompt_err_ret, sizeof (nh_g->l_role_c_root_plselection_prompt_err_ret));
    if (&nh_tmpl_s_save_c_saveprocs)
        memcpy(&(nh_g->s_save_c_saveprocs), &nh_tmpl_s_save_c_saveprocs, sizeof (nh_g->s_save_c_saveprocs));
    if (&nh_tmpl_s_save_c_bw_fd)
        memcpy(&(nh_g->s_save_c_bw_fd), &nh_tmpl_s_save_c_bw_fd, sizeof (nh_g->s_save_c_bw_fd));
    if (&nh_tmpl_s_shk_c_sell_response)
        memcpy(&(nh_g->s_shk_c_sell_response), &nh_tmpl_s_shk_c_sell_response, sizeof (nh_g->s_shk_c_sell_response));
    if (&nh_tmpl_s_shk_c_sell_how)
        memcpy(&(nh_g->s_shk_c_sell_how), &nh_tmpl_s_shk_c_sell_how, sizeof (nh_g->s_shk_c_sell_how));
    if (&nh_tmpl_Izchak_speaks)
        memcpy(&Izchak_speaks, &nh_tmpl_Izchak_speaks, sizeof Izchak_speaks);
    if (&nh_tmpl_s_sp_lev_c_ralign)
        memcpy(&(nh_g->s_sp_lev_c_ralign), &nh_tmpl_s_sp_lev_c_ralign, sizeof (nh_g->s_sp_lev_c_ralign));
    if (&nh_tmpl_s_timeout_c_timer_id)
        memcpy(&(nh_g->s_timeout_c_timer_id), &nh_tmpl_s_timeout_c_timer_id, sizeof (nh_g->s_timeout_c_timer_id));
    if (&nh_tmpl_s_topten_c_toptenwin)
        memcpy(&(nh_g->s_topten_c_toptenwin), &nh_tmpl_s_topten_c_toptenwin, sizeof (nh_g->s_topten_c_toptenwin));
    if (&nh_tmpl_s_trap_c_acid_ctx)
        memcpy(&(nh_g->s_trap_c_acid_ctx), &nh_tmpl_s_trap_c_acid_ctx, sizeof (nh_g->s_trap_c_acid_ctx));
    if (&nh_tmpl_s_u_init_c_Archeologist)
        memcpy(&(nh_g->s_u_init_c_Archeologist), &nh_tmpl_s_u_init_c_Archeologist, sizeof (nh_g->s_u_init_c_Archeologist));
    if (&nh_tmpl_s_u_init_c_Barbarian)
        memcpy(&(nh_g->s_u_init_c_Barbarian), &nh_tmpl_s_u_init_c_Barbarian, sizeof (nh_g->s_u_init_c_Barbarian));
    if (&nh_tmpl_s_u_init_c_Cave_man)
        memcpy(&(nh_g->s_u_init_c_Cave_man), &nh_tmpl_s_u_init_c_Cave_man, sizeof (nh_g->s_u_init_c_Cave_man));
    if (&nh_tmpl_s_u_init_c_Healer)
        memcpy(&(nh_g->s_u_init_c_Healer), &nh_tmpl_s_u_init_c_Healer, sizeof (nh_g->s_u_init_c_Healer));
    if (&nh_tmpl_s_u_init_c_Knight)
        memcpy(&(nh_g->s_u_init_c_Knight), &nh_tmpl_s_u_init_c_Knight, sizeof (nh_g->s_u_init_c_Knight));
    if (&nh_tmpl_s_u_init_c_Monk)
        memcpy(&(nh_g->s_u_init_c_Monk), &nh_tmpl_s_u_init_c_Monk, sizeof (nh_g->s_u_init_c_Monk));
    if (&nh_tmpl_s_u_init_c_Priest)
        memcpy(&(nh_g->s_u_init_c_Priest), &nh_tmpl_s_u_init_c_Priest, sizeof (nh_g->s_u_init_c_Priest));
    if (&nh_tmpl_s_u_init_c_Ranger)
        memcpy(&(nh_g->s_u_init_c_Ranger), &nh_tmpl_s_u_init_c_Ranger, sizeof (nh_g->s_u_init_c_Ranger));
    if (&nh_tmpl_s_u_init_c_Rogue)
        memcpy(&(nh_g->s_u_init_c_Rogue), &nh_tmpl_s_u_init_c_Rogue, sizeof (nh_g->s_u_init_c_Rogue));
    if (&nh_tmpl_s_u_init_c_Samurai)
        memcpy(&(nh_g->s_u_init_c_Samurai), &nh_tmpl_s_u_init_c_Samurai, sizeof (nh_g->s_u_init_c_Samurai));
    if (&nh_tmpl_s_u_init_c_Tourist)
        memcpy(&(nh_g->s_u_init_c_Tourist), &nh_tmpl_s_u_init_c_Tourist, sizeof (nh_g->s_u_init_c_Tourist));
    if (&nh_tmpl_s_u_init_c_Valkyrie)
        memcpy(&(nh_g->s_u_init_c_Valkyrie), &nh_tmpl_s_u_init_c_Valkyrie, sizeof (nh_g->s_u_init_c_Valkyrie));
    if (&nh_tmpl_s_u_init_c_Wizard)
        memcpy(&(nh_g->s_u_init_c_Wizard), &nh_tmpl_s_u_init_c_Wizard, sizeof (nh_g->s_u_init_c_Wizard));
    if (&nh_tmpl_s_u_init_c_Tinopener)
        memcpy(&(nh_g->s_u_init_c_Tinopener), &nh_tmpl_s_u_init_c_Tinopener, sizeof (nh_g->s_u_init_c_Tinopener));
    if (&nh_tmpl_s_u_init_c_Magicmarker)
        memcpy(&(nh_g->s_u_init_c_Magicmarker), &nh_tmpl_s_u_init_c_Magicmarker, sizeof (nh_g->s_u_init_c_Magicmarker));
    if (&nh_tmpl_s_u_init_c_Lamp)
        memcpy(&(nh_g->s_u_init_c_Lamp), &nh_tmpl_s_u_init_c_Lamp, sizeof (nh_g->s_u_init_c_Lamp));
    if (&nh_tmpl_s_u_init_c_Blindfold)
        memcpy(&(nh_g->s_u_init_c_Blindfold), &nh_tmpl_s_u_init_c_Blindfold, sizeof (nh_g->s_u_init_c_Blindfold));
    if (&nh_tmpl_s_u_init_c_Instrument)
        memcpy(&(nh_g->s_u_init_c_Instrument), &nh_tmpl_s_u_init_c_Instrument, sizeof (nh_g->s_u_init_c_Instrument));
    if (&nh_tmpl_s_u_init_c_Xtra_food)
        memcpy(&(nh_g->s_u_init_c_Xtra_food), &nh_tmpl_s_u_init_c_Xtra_food, sizeof (nh_g->s_u_init_c_Xtra_food));
    if (&nh_tmpl_s_u_init_c_Leash)
        memcpy(&(nh_g->s_u_init_c_Leash), &nh_tmpl_s_u_init_c_Leash, sizeof (nh_g->s_u_init_c_Leash));
    if (&nh_tmpl_s_u_init_c_Towel)
        memcpy(&(nh_g->s_u_init_c_Towel), &nh_tmpl_s_u_init_c_Towel, sizeof (nh_g->s_u_init_c_Towel));
    if (&nh_tmpl_s_u_init_c_Wishing)
        memcpy(&(nh_g->s_u_init_c_Wishing), &nh_tmpl_s_u_init_c_Wishing, sizeof (nh_g->s_u_init_c_Wishing));
    if (&nh_tmpl_s_u_init_c_Money)
        memcpy(&(nh_g->s_u_init_c_Money), &nh_tmpl_s_u_init_c_Money, sizeof (nh_g->s_u_init_c_Money));
    if (&nh_tmpl_l_u_init_c_ini_inv_nocreate)
        memcpy(&(nh_g->l_u_init_c_ini_inv_nocreate), &nh_tmpl_l_u_init_c_ini_inv_nocreate, sizeof (nh_g->l_u_init_c_ini_inv_nocreate));
    if (&nh_tmpl_l_u_init_c_ini_inv_nocreate2)
        memcpy(&(nh_g->l_u_init_c_ini_inv_nocreate2), &nh_tmpl_l_u_init_c_ini_inv_nocreate2, sizeof (nh_g->l_u_init_c_ini_inv_nocreate2));
    if (&nh_tmpl_l_u_init_c_ini_inv_nocreate3)
        memcpy(&(nh_g->l_u_init_c_ini_inv_nocreate3), &nh_tmpl_l_u_init_c_ini_inv_nocreate3, sizeof (nh_g->l_u_init_c_ini_inv_nocreate3));
    if (&nh_tmpl_l_u_init_c_ini_inv_nocreate4)
        memcpy(&(nh_g->l_u_init_c_ini_inv_nocreate4), &nh_tmpl_l_u_init_c_ini_inv_nocreate4, sizeof (nh_g->l_u_init_c_ini_inv_nocreate4));
    if (&nh_tmpl_circle_data)
        memcpy(&circle_data, &nh_tmpl_circle_data, sizeof circle_data);
    if (&nh_tmpl_circle_start)
        memcpy(&circle_start, &nh_tmpl_circle_start, sizeof circle_start);
    if (&nh_tmpl_l_windows_c_genl_status_update_fieldorder)
        memcpy(&(nh_g->l_windows_c_genl_status_update_fieldorder), &nh_tmpl_l_windows_c_genl_status_update_fieldorder, sizeof (nh_g->l_windows_c_genl_status_update_fieldorder));
    if (&nh_tmpl_tc_lcl_data)
        memcpy(&(nh_g->tc_lcl_data), &nh_tmpl_tc_lcl_data, sizeof (nh_g->tc_lcl_data));
    if (&nh_tmpl_s_termcap_c_nullstr)
        memcpy(&(nh_g->s_termcap_c_nullstr), &nh_tmpl_s_termcap_c_nullstr, sizeof (nh_g->s_termcap_c_nullstr));
    if (&nh_tmpl_s_termcap_c_adef_nilstring)
        memcpy(&(nh_g->s_termcap_c_adef_nilstring), &nh_tmpl_s_termcap_c_adef_nilstring, sizeof (nh_g->s_termcap_c_adef_nilstring));
    if (&nh_tmpl_s_termcap_c_nulstr)
        memcpy(&(nh_g->s_termcap_c_nulstr), &nh_tmpl_s_termcap_c_nulstr, sizeof (nh_g->s_termcap_c_nulstr));
    if (&nh_tmpl_tty_procs)
        memcpy(&tty_procs, &nh_tmpl_tty_procs, sizeof tty_procs);
    if (&nh_tmpl_s_wintty_c_winpanicstr)
        memcpy(&(nh_g->s_wintty_c_winpanicstr), &nh_tmpl_s_wintty_c_winpanicstr, sizeof (nh_g->s_wintty_c_winpanicstr));
    if (&nh_tmpl_defmorestr)
        memcpy(&defmorestr, &nh_tmpl_defmorestr, sizeof defmorestr);
    if (nh_init_artifact_c)
        nh_init_artifact_c();
    if (nh_init_attrib_c)
        nh_init_attrib_c();
    if (nh_init_cmd_c)
        nh_init_cmd_c();
    if (nh_init_decl_c)
        nh_init_decl_c();
    if (nh_init_detect_c)
        nh_init_detect_c();
    if (nh_init_dungeon_c)
        nh_init_dungeon_c();
    if (nh_init_end_c)
        nh_init_end_c();
    if (nh_init_mkmaze_c)
        nh_init_mkmaze_c();
    if (nh_init_options_c)
        nh_init_options_c();
    if (nh_init_windows_c)
        nh_init_windows_c();
    if (nh_init_worn_c)
        nh_init_worn_c();
}

#ifdef NH_GLOBALS_STANDALONE
/* Single-context programs (the build-time utilities): give them one
 * context before main() runs. */
static struct nh_globals nh_standalone_ctx;
__attribute__((constructor)) static void
nh_globals_standalone(void)
{
    nh_globals_init(&nh_standalone_ctx);
}
#endif
