/* nh_globals.h -- every mutable file-scope / function-static object of the
 * game, collected into one per-environment struct.
 *
 * GENERATED by tools/collect_globals -- do not edit by hand. Re-run the
 * tool on a pristine tree instead.
 *
 * Access goes through the thread-local pointer `nh_g`: object-like macros
 * (below) keep the original identifiers working for most objects; the
 * ones whose names collide with struct fields or other identifiers were
 * rewritten at every reference to `nh_g->name`. */
#ifndef NH_GLOBALS_H
#define NH_GLOBALS_H

#include "artifact.h"
#include "func_tab.h"
#include <time.h>
#include <fcntl.h>
#include "lev.h"
#include "qtext.h"
#include "dlb.h"
#include "isaac64.h"
#include <stdio.h>
#include <termios.h>
#include "tcap.h"

/* opaque types only pointed to from the struct */
struct ext_func_tab;
struct bubble;
struct passwd;
struct WinDesc;
struct DisplayDesc;

/* --- types hoisted from their defining .c files -------------------- */
/* from src/apply.c */
struct trapinfo {
    struct obj *tobj;
    xchar tx, ty;
    int time_needed;
    boolean force_bungle;
};

/* from src/artifact.c */
struct abil2spfx_tag {
        long *abil;
        unsigned long spfx;
    };

/* from src/attrib.c */
struct innate {
    schar ulevel;
    long *ability;
    const char *gainstr, *losestr;
};

/* from src/botl.c */
#ifndef MAXVALWIDTH
#define MAXVALWIDTH 80
#endif
struct hilite_s {
    enum statusfields fld;
    boolean set;
    unsigned anytype;
    anything value;
    int behavior;
    char textmatch[MAXVALWIDTH];
    enum relationships rel;
    int coloridx;
    struct hilite_s *next;
};

/* from src/botl.c */
struct istat_s {
    const char *fldname;
    const char *fldfmt;
    long time;  /* moves when this field hilite times out */
    boolean chg; /* need to recalc time? */
    boolean percent_matters;
    short percent_value;
    unsigned anytype;
    anything a;
    char *val;
    int valwidth;
    enum statusfields idxmax;
    enum statusfields fld;
#ifdef STATUS_HILITES
    struct hilite_s *hilite_rule; /* the entry, if any, in 'thresholds'
                                   * list that currently applies        */
    struct hilite_s *thresholds;
#endif
};

/* from src/botl.c */
struct _status_hilite_line_str {
    int id;
    int fld;
    struct hilite_s *hl;
    unsigned long mask;
    char str[BUFSZ];
    struct _status_hilite_line_str *next;
};

/* from src/dbridge.c */
struct entity {
    struct monst *emon;     /* youmonst for the player */
    struct permonst *edata; /* must be non-zero for record to be valid */
    int ex, ey;
};

/* from src/detect.c */
struct nh_anon_s_detect_c_level_detects {
    const char *what;
    d_level *where;
};

/* from src/display.c */
#ifndef TMP_AT_MAX_GLYPHS
#define TMP_AT_MAX_GLYPHS (COLNO * 2)
#endif
struct tmp_glyph {
    coord saved[TMP_AT_MAX_GLYPHS]; /* previously updated positions */
    int sidx;                       /* index of next unused slot in saved[] */
    int style; /* either DISP_BEAM or DISP_FLASH or DISP_ALWAYS */
    int glyph; /* glyph to use when printing */
    struct tmp_glyph *prev;
};

/* from src/display.c */
#ifdef __cplusplus
#define new nh_cxx_new_
#endif
typedef struct {
    xchar new; /* perhaps move this bit into the rm structure. */
    int glyph;
} gbuf_entry;
#ifdef __cplusplus
#undef new
#endif

/* from src/dungeon.c */
struct level_map {
    const char *lev_name;
    d_level *lev_spec;
};

/* from src/end.c */
struct valuable_data {
    long count;
    int typ;
};

/* from src/end.c */
struct val_list {
    struct valuable_data *list;
    int size;
};

/* from src/extralev.c */
struct rogueroom {
    xchar rlx, rly;
    xchar dx, dy;
    boolean real;
    uchar doortable;
    int nroom; /* Only meaningful for "real" rooms */
};

/* from src/files.c */
struct _config_error_frame {
    int line_num;
    int num_errors;
    boolean origline_shown;
    boolean fromfile;
    boolean secure;
    char origline[4 * BUFSZ];
    char source[BUFSZ];
    struct _config_error_frame *next;
};

/* from src/invent.c */
struct xprnctx {
    char let;
    boolean dot;
};

/* from src/lock.c */
struct xlock_s {
    struct rm *door;
    struct obj *box;
    int picktyp, /* key|pick|card for unlock, sharp vs blunt for #force */
        chance, usedtime;
    boolean magic_key;
};

/* from src/makemon.c */
struct nh_anon_s_makemon_c_rndmonst_state {
    int choice_count;
    char mchoices[SPECIAL_PM]; /* value range is 0..127 */
};

/* from src/muse.c */
struct musable {
    struct obj *offensive;
    struct obj *defensive;
    struct obj *misc;
    int has_offense, has_defense, has_misc;
    /* =0, no capability; otherwise, different numbers.
     * If it's an object, the object is also set (it's 0 otherwise).
     */
};

/* from src/objnam.c */
struct Jitem {
    int item;
    const char *name;
};

/* from src/objnam.c */
struct sing_plur {
    const char *sing, *plur;
};

/* from src/options.c */
struct Bool_Opt {
    const char *name;
    boolean *addr, initvalue;
    int optflags;
};

/* from src/options.c */
struct Comp_Opt {
    const char *name, *descr;
    int size; /* for frontends and such allocating space --
               * usually allowed size of data in game, but
               * occasionally maximum reasonable size for
               * typing when game maintains information in
               * a different format */
    int optflags;
};

/* from src/read.c */
struct litmon {
    struct monst *mon;
    struct litmon *nxt;
};

/* from src/restore.c */
struct restore_procs {
    const char *name;
    int mread_flags;
    void NDECL((*restore_minit));
    void FDECL((*restore_mread), (int, genericptr_t, unsigned int));
    void FDECL((*restore_bclose), (int));
};

/* from src/restore.c */
#ifndef N_PER_BUCKET
#define N_PER_BUCKET 64
#endif
struct bucket {
    struct bucket *next;
    struct {
        unsigned gid; /* ghost ID */
        unsigned nid; /* new ID */
    } map[N_PER_BUCKET];
};

/* from src/rnd.c */
struct rnglist_t {
    int FDECL((*fn), (int));
    boolean init;
    isaac64_ctx rng_state;
};

/* from src/save.c */
struct save_procs {
    const char *name;
    void FDECL((*save_bufon), (int));
    void FDECL((*save_bufoff), (int));
    void FDECL((*save_bflush), (int));
    void FDECL((*save_bwrite), (int, genericptr_t, unsigned int));
    void FDECL((*save_bclose), (int));
};

/* from src/shk.c */
struct repo { /* repossession context */
    struct monst *shopkeeper;
    coord location;
};

/* from src/spell.c */
struct tport_hideaway {
        struct spell savespell;
        int tport_indx;
    };

/* from src/topten.c */
#ifndef ROLESZ
#define ROLESZ 3
#endif
#ifndef NAMSZ
#define NAMSZ 10
#endif
#ifndef DTHSZ
#define DTHSZ 100
#endif
struct toptenentry {
    struct toptenentry *tt_next;
#ifdef UPDATE_RECORD_IN_PLACE
    long fpos;
#endif
    long points;
    int deathdnum, deathlev;
    int maxlvl, hp, maxhp, deaths;
    int ver_major, ver_minor, patchlevel;
    long deathdate, birthdate;
    int uid;
    char plrole[ROLESZ + 1];
    char plrace[ROLESZ + 1];
    char plgend[ROLESZ + 1];
    char plalign[ROLESZ + 1];
    char name[NAMSZ + 1];
    char death[DTHSZ + 1];
};

/* from src/trap.c */
struct nh_anon_s_trap_c_launchplace {
    struct obj *obj;
    xchar x, y;
};

/* from src/trap.c */
struct h2o_ctx {
    int dkn_boom, unk_boom; /* track dknown, !dknown separately */
    boolean ctx_valid;
};

/* from src/u_init.c */
struct trobj {
    short trotyp;
    schar trspe;
    char trclass;
    Bitfield(trquan, 6);
    Bitfield(trbless, 2);
};

/* from src/windows.c */
struct win_choices {
    struct window_procs *procs;
    void FDECL((*ini_routine), (int)); /* optional (can be 0) */
#ifdef WINCHAIN
    void *FDECL((*chain_routine), (int, int, void *, void *, void *));
#endif
};

/* from src/worm.c */
struct wseg {
    struct wseg *nseg;
    xchar wx, wy; /* the segment's position */
};

/* from src/worn.c */
struct worn {
    long w_mask;
    struct obj **w_obj;
};

struct nh_globals {
    /* ---- include/artilist.h ---- */
    struct artifact s_artilist_h_artilist[35]; /* static artilist */
    /* ---- src/apply.c ---- */
    int s_apply_c_jumping_is_magic; /* static jumping_is_magic */
    struct trapinfo s_apply_c_trapinfo; /* static trapinfo */
    int s_apply_c_polearm_range_min; /* static polearm_range_min */
    int s_apply_c_polearm_range_max; /* static polearm_range_max */
    /* ---- src/artifact.c ---- */
    int s_artifact_c_spec_dbon_applies; /* static spec_dbon_applies */
    boolean s_artifact_c_artiexist[1+NROFARTIFACTS+1]; /* static artiexist */
    xchar s_artifact_c_artidisco[NROFARTIFACTS]; /* static artidisco */
    boolean s_artifact_c_touch_blasted; /* static touch_blasted */
    struct abil2spfx_tag l_artifact_c_abil_to_spfx_abil2spfx[12]; /* abil_to_spfx(): static abil2spfx */
    char l_artifact_c_glow_verb_resbuf[20]; /* glow_verb(): static resbuf */
    int l_artifact_c_retouch_equipment_nesting; /* retouch_equipment(): static nesting */
    int s_artifact_c_mkot_trap_warn_count; /* static mkot_trap_warn_count */
    /* ---- src/attrib.c ---- */
    struct innate s_attrib_c_arc_abil[4]; /* static arc_abil */
    struct innate s_attrib_c_bar_abil[4]; /* static bar_abil */
    struct innate s_attrib_c_cav_abil[3]; /* static cav_abil */
    struct innate s_attrib_c_hea_abil[3]; /* static hea_abil */
    struct innate s_attrib_c_kni_abil[2]; /* static kni_abil */
    struct innate s_attrib_c_mon_abil[12]; /* static mon_abil */
    struct innate s_attrib_c_pri_abil[3]; /* static pri_abil */
    struct innate s_attrib_c_ran_abil[4]; /* static ran_abil */
    struct innate s_attrib_c_rog_abil[3]; /* static rog_abil */
    struct innate s_attrib_c_sam_abil[3]; /* static sam_abil */
    struct innate s_attrib_c_tou_abil[3]; /* static tou_abil */
    struct innate s_attrib_c_val_abil[4]; /* static val_abil */
    struct innate s_attrib_c_wiz_abil[3]; /* static wiz_abil */
    struct innate s_attrib_c_dwa_abil[2]; /* static dwa_abil */
    struct innate s_attrib_c_elf_abil[3]; /* static elf_abil */
    struct innate s_attrib_c_gno_abil[2]; /* static gno_abil */
    struct innate s_attrib_c_orc_abil[3]; /* static orc_abil */
    struct innate s_attrib_c_hum_abil[1]; /* static hum_abil */
    char l_attrib_c_from_what_buf[BUFSZ]; /* from_what(): static buf */
    /* ---- src/ball.c ---- */
    int s_ball_c_bcrestriction; /* static bcrestriction */
    /* ---- src/botl.c ---- */
    int s_botl_c_mrank_sz; /* static mrank_sz */
    char l_botl_c_get_strength_str_buf[32]; /* get_strength_str(): static buf */
    char l_botl_c_do_statusline1_newbot1[BUFSZ]; /* do_statusline1(): static newbot1 */
    char l_botl_c_do_statusline2_newbot2[BUFSZ]; /* do_statusline2(): static newbot2 */
    char l_botl_c_do_statusline2_dloc[QBUFSZ]; /* do_statusline2(): static dloc */
    char l_botl_c_do_statusline2_hlth[QBUFSZ]; /* do_statusline2(): static hlth */
    char l_botl_c_do_statusline2_expr[QBUFSZ]; /* do_statusline2(): static expr */
    char l_botl_c_do_statusline2_tmmv[QBUFSZ]; /* do_statusline2(): static tmmv */
    char l_botl_c_do_statusline2_cond[QBUFSZ]; /* do_statusline2(): static cond */
    struct istat_s blstats[2][MAXBLSTATS]; /* blstats */
    boolean s_botl_c_blinit; /* static blinit */
    boolean s_botl_c_update_all; /* static update_all */
    boolean s_botl_c_valset[MAXBLSTATS]; /* static valset */
    long s_botl_c_bl_hilite_moves; /* static bl_hilite_moves */
    unsigned long s_botl_c_cond_hilites[BL_ATTCLR_MAX]; /* static cond_hilites */
    int s_botl_c_now_or_before_idx; /* static now_or_before_idx */
    int l_botl_c_eval_notify_windowport_field_oldrndencode; /* eval_notify_windowport_field(): static oldrndencode */
    nhsym l_botl_c_eval_notify_windowport_field_oldgoldsym; /* eval_notify_windowport_field(): static oldgoldsym */
    boolean l_botl_c_init_blstats_initalready; /* init_blstats(): static initalready */
    struct hilite_s status_hilites[MAXBLSTATS]; /* status_hilites */
    char *l_botl_c_splitsubfields_subfields[16]; /* splitsubfields(): static subfields */
    const char *l_botl_c_parse_status_hl2_aligntxt[3]; /* parse_status_hl2(): static aligntxt */
    const char *l_botl_c_parse_status_hl2_hutxt[7]; /* parse_status_hl2(): static hutxt */
    char l_botl_c_conditionbitmask2str_buf[BUFSZ]; /* conditionbitmask2str(): static buf */
    struct _status_hilite_line_str *s_botl_c_status_hilite_str; /* static status_hilite_str */
    int s_botl_c_status_hilite_str_id; /* static status_hilite_str_id */
    char l_botl_c_status_hilite2str_buf[BUFSZ]; /* status_hilite2str(): static buf */
    const char *l_botl_c_status_hilite_menu_add_aligntxt[3]; /* status_hilite_menu_add(): static aligntxt */
    const char *l_botl_c_status_hilite_menu_add_hutxt[7]; /* status_hilite_menu_add(): static hutxt */
    /* ---- src/cmd.c ---- */
    boolean s_cmd_c_alt_esc; /* static alt_esc */
    struct cmd Cmd; /* Cmd */
    int (*s_cmd_c_timed_occ_fn)(void); /* static timed_occ_fn */
    const char *s_cmd_c_readchar_queue; /* static readchar_queue */
    coord s_cmd_c_clicklook_cc; /* static clicklook_cc */
    char s_cmd_c_pushq[20]; /* static pushq */
    char s_cmd_c_saveq[20]; /* static saveq */
    int s_cmd_c_phead; /* static phead */
    int s_cmd_c_ptail; /* static ptail */
    int s_cmd_c_shead; /* static shead */
    int s_cmd_c_stail; /* static stail */
    winid s_cmd_c_en_win; /* static en_win */
    boolean s_cmd_c_en_via_menu; /* static en_via_menu */
    char l_cmd_c_basics_enlightenment_Power[28]; /* basics_enlightenment(): static Power */
    struct ext_func_tab extcmdlist[113]; /* extcmdlist */
    int extcmdlist_length; /* extcmdlist_length */
    char l_cmd_c_key2extcmddesc_key2cmdbuf[48]; /* key2extcmddesc(): static key2cmdbuf */
    struct ext_func_tab *l_cmd_c_reset_commands_back_dir_cmd[8]; /* reset_commands(): static back_dir_cmd */
    boolean l_cmd_c_reset_commands_backed_dir_cmd; /* reset_commands(): static backed_dir_cmd */
    unsigned int l_cmd_c_randomkey_i; /* randomkey(): static i */
    int s_cmd_c_last_multi; /* static last_multi */
    char l_cmd_c_click_to_cmd_cmd[4]; /* click_to_cmd(): static cmd */
    char l_cmd_c_parse_in_line[COLNO]; /* parse(): static in_line */
    char l_cmd_c_dotravel_cmd[2]; /* dotravel(): static cmd */
    /* ---- src/dbridge.c ---- */
    struct entity s_dbridge_c_occupants[2]; /* static occupants */
    char l_dbridge_c_E_phrase_wholebuf[80]; /* E_phrase(): static wholebuf */
    /* ---- src/decl.c ---- */
    int (*afternmv)(void); /* afternmv */
    int (*occupation)(void); /* occupation */
    const char *hname; /* hname */
    int hackpid; /* hackpid */
    int locknum; /* locknum */
    char chosen_windowtype[WINTYPELEN]; /* chosen_windowtype */
    int bases[MAXOCLASSES]; /* bases */
    int multi; /* multi */
    const char *multi_reason; /* multi_reason */
    int nroom; /* nroom */
    int nsubroom; /* nsubroom */
    int occtime; /* occtime */
    int x_maze_max; /* x_maze_max */
    int y_maze_max; /* y_maze_max */
    int otg_temp; /* otg_temp */
    int in_doagain; /* in_doagain */
    struct dgn_topology dungeon_topology; /* dungeon_topology */
    struct q_score quest_status; /* quest_status */
    int warn_obj_cnt; /* warn_obj_cnt */
    int smeq[MAXNROFROOMS+1]; /* smeq */
    int doorindex; /* doorindex */
    char *save_cm; /* save_cm */
    struct kinfo killer; /* killer */
    long done_money; /* done_money */
    const char *nomovemsg; /* nomovemsg */
    char plname[PL_NSIZ]; /* plname */
    char pl_character[PL_CSIZ]; /* pl_character */
    char pl_race; /* pl_race */
    char pl_fruit[PL_FSIZ]; /* pl_fruit */
    struct fruit *ffruit; /* ffruit */
    char tune[6]; /* tune */
    boolean ransacked; /* ransacked */
    const char *occtxt; /* occtxt */
    long yn_number; /* yn_number */
    struct linfo level_info[MAXLINFO]; /* level_info */
    struct sinfo program_state; /* program_state */
    schar tbx; /* tbx */
    schar tby; /* tby */
    struct multishot m_shot; /* m_shot */
    dungeon dungeons[MAXDUNGEON]; /* dungeons */
    s_level *sp_levchn; /* sp_levchn */
    stairway upstair; /* upstair */
    stairway dnstair; /* dnstair */
    stairway upladder; /* upladder */
    stairway dnladder; /* dnladder */
    stairway sstairs; /* sstairs */
    dest_area updest; /* updest */
    dest_area dndest; /* dndest */
    coord inv_pos; /* inv_pos */
    boolean defer_see_monsters; /* defer_see_monsters */
    boolean in_mklev; /* in_mklev */
    boolean stoned; /* stoned */
    boolean unweapon; /* unweapon */
    boolean mrg_to_wielded; /* mrg_to_wielded */
    boolean in_steed_dismounting; /* in_steed_dismounting */
    boolean has_strong_rngseed; /* has_strong_rngseed */
    coord bhitpos; /* bhitpos */
    coord doors[DOORMAX]; /* doors */
    struct mkroom rooms[(MAXNROFROOMS+1)*2]; /* rooms */
    struct mkroom *subrooms; /* subrooms */
    struct mkroom *upstairs_room; /* upstairs_room */
    struct mkroom *dnstairs_room; /* dnstairs_room */
    struct mkroom *sstairs_room; /* sstairs_room */
    dlevel_t level; /* level */
    struct trap *ftrap; /* ftrap */
    struct monst youmonst; /* youmonst */
    struct context_info context; /* context */
    struct flag flags; /* flags */
    struct instance_flags iflags; /* iflags */
    struct you u; /* u */
    time_t ubirthday; /* ubirthday */
    struct u_realtime urealtime; /* urealtime */
    schar lastseentyp[COLNO][ROWNO]; /* lastseentyp */
    struct obj *invent; /* invent */
    struct obj *uwep; /* uwep */
    struct obj *uarm; /* uarm */
    struct obj *uswapwep; /* uswapwep */
    struct obj *uquiver; /* uquiver */
    struct obj *uarmu; /* uarmu */
    struct obj *uskin; /* uskin */
    struct obj *uarmc; /* uarmc */
    struct obj *uarmh; /* uarmh */
    struct obj *uarms; /* uarms */
    struct obj *uarmg; /* uarmg */
    struct obj *uarmf; /* uarmf */
    struct obj *uamul; /* uamul */
    struct obj *uright; /* uright */
    struct obj *uleft; /* uleft */
    struct obj *ublindf; /* ublindf */
    struct obj *uchain; /* uchain */
    struct obj *uball; /* uball */
    struct obj *current_wand; /* current_wand */
    struct obj *thrownobj; /* thrownobj */
    struct obj *kickedobj; /* kickedobj */
    struct spell spl_book[MAXSPELL+1]; /* spl_book */
    long moves; /* moves */
    long monstermoves; /* monstermoves */
    long wailmsg; /* wailmsg */
    struct obj *migrating_objs; /* migrating_objs */
    struct obj *billobjs; /* billobjs */
    char dogname[PL_PSIZ]; /* dogname */
    char catname[PL_PSIZ]; /* catname */
    char horsename[PL_PSIZ]; /* horsename */
    char preferred_pet; /* preferred_pet */
    struct monst *mydogs; /* mydogs */
    struct monst *migrating_mons; /* migrating_mons */
    struct autopickup_exception *apelist; /* apelist */
    struct mvitals mvitals[NUMMONS]; /* mvitals */
    long domove_attempting; /* domove_attempting */
    long domove_succeeded; /* domove_succeeded */
    struct c_color_names c_color_names; /* c_color_names */
    struct menucoloring *menu_colorings; /* menu_colorings */
    const char *c_obj_colors[16]; /* c_obj_colors */
    struct c_common_strings c_common_strings; /* c_common_strings */
    const char *materialnm[22]; /* materialnm */
    boolean vision_full_recalc; /* vision_full_recalc */
    char **viz_array; /* viz_array */
    winid WIN_MESSAGE; /* WIN_MESSAGE */
    winid WIN_STATUS; /* WIN_STATUS */
    winid WIN_MAP; /* WIN_MAP */
    winid WIN_INVEN; /* WIN_INVEN */
    char toplines[TBUFSZ]; /* toplines */
    struct tc_gbl_data tc_gbl_data; /* tc_gbl_data */
    char *fqn_prefix[PREFIX_COUNT]; /* fqn_prefix */
    const char *fqn_prefix_names[PREFIX_COUNT]; /* fqn_prefix_names */
    struct savefile_info sfcap; /* sfcap */
    struct savefile_info sfrestinfo; /* sfrestinfo */
    struct savefile_info sfsaveinfo; /* sfsaveinfo */
    struct plinemsg_type *plinemsg_types; /* plinemsg_types */
    const char *ARGV0; /* ARGV0 */
    unsigned int nhUse_dummy; /* nhUse_dummy */
    /* ---- src/detect.c ---- */
    struct nh_anon_s_detect_c_level_detects s_detect_c_level_detects[4]; /* static level_detects */
    /* ---- src/dig.c ---- */
    boolean s_dig_c_did_dig_msg; /* static did_dig_msg */
    /* ---- src/display.c ---- */
    struct tmp_glyph s_display_c_tgfirst; /* static tgfirst */
    struct tmp_glyph *l_display_c_tmp_at_tglyph; /* tmp_at(): static tglyph */
    xchar l_display_c_swallowed_lastx; /* swallowed(): static lastx */
    xchar l_display_c_swallowed_lasty; /* swallowed(): static lasty */
    xchar l_display_c_under_water_lastx; /* under_water(): static lastx */
    xchar l_display_c_under_water_lasty; /* under_water(): static lasty */
    boolean l_display_c_under_water_dela; /* under_water(): static dela */
    boolean l_display_c_under_ground_dela; /* under_ground(): static dela */
    gbuf_entry s_display_c_gbuf[ROWNO][COLNO]; /* static gbuf */
    char s_display_c_gbuf_start[ROWNO]; /* static gbuf_start */
    char s_display_c_gbuf_stop[ROWNO]; /* static gbuf_stop */
    boolean l_display_c_cls_in_cls; /* cls(): static in_cls */
    int l_display_c_flush_screen_flushing; /* flush_screen(): static flushing */
    int l_display_c_flush_screen_delay_flushing; /* flush_screen(): static delay_flushing */
    unsigned char seenv_matrix[3][3]; /* seenv_matrix */
    /* ---- src/do.c ---- */
    boolean s_do_c_at_ladder; /* static at_ladder */
    d_level save_dlevel; /* save_dlevel */
    char *s_do_c_dfr_pre_msg; /* static dfr_pre_msg */
    char *s_do_c_dfr_post_msg; /* static dfr_post_msg */
    char l_do_c_dowipe_buf[39]; /* dowipe(): static buf */
    /* ---- src/do_name.c ---- */
    char l_do_name_c_nextmbuf_bufs[5][256]; /* nextmbuf(): static bufs */
    int l_do_name_c_nextmbuf_bufidx; /* nextmbuf(): static bufidx */
    void (*s_do_name_c_getpos_hilitefunc)(int); /* static getpos_hilitefunc */
    boolean (*s_do_name_c_getpos_getvalid)(int, int); /* static getpos_getvalid */
    struct opvar *s_do_name_c_gloc_filter_map; /* static gloc_filter_map */
    int s_do_name_c_gloc_filter_floodfill_match_glyph; /* static gloc_filter_floodfill_match_glyph */
    char l_do_name_c_dxdy_to_dist_descr_buf[30]; /* dxdy_to_dist_descr(): static buf */
    char l_do_name_c_coord_desc_screen_fmt[16]; /* coord_desc(): static screen_fmt */
    int s_do_name_c_via_naming; /* static via_naming */
    char l_do_name_c_rndmonnam_buf[BUFSZ]; /* rndmonnam(): static buf */
    /* ---- src/do_wear.c ---- */
    boolean s_do_wear_c_initial_don; /* static initial_don */
    int s_do_wear_c_Narmorpieces; /* static Narmorpieces */
    int s_do_wear_c_Naccessories; /* static Naccessories */
    char l_do_wear_c_armoroff_offdelaybuf[60]; /* armoroff(): static offdelaybuf */
    /* ---- src/dog.c ---- */
    int l_dog_c_makedog_petname_used; /* makedog(): static petname_used */
    /* ---- src/dogmove.c ---- */
    xchar s_dogmove_c_gtyp; /* static gtyp */
    xchar s_dogmove_c_gx; /* static gx */
    xchar s_dogmove_c_gy; /* static gy */
    /* ---- src/dokick.c ---- */
    struct rm *s_dokick_c_maploc; /* static maploc */
    struct rm s_dokick_c_nowhere; /* static nowhere */
    const char *s_dokick_c_gate_str; /* static gate_str */
    /* ---- src/dothrow.c ---- */
    long l_dothrow_c_breakobj_lastmovetime; /* breakobj(): static lastmovetime */
    boolean l_dothrow_c_breakobj_peaceful_shk; /* breakobj(): static peaceful_shk */
    /* ---- src/drawing.c ---- */
    struct symsetentry symset[NUM_GRAPHICS]; /* symset */
    int currentgraphics; /* currentgraphics */
    nhsym showsyms[SYM_MAX]; /* showsyms */
    nhsym primary_syms[SYM_MAX]; /* primary_syms */
    nhsym rogue_syms[SYM_MAX]; /* rogue_syms */
    nhsym ov_primary_syms[SYM_MAX]; /* ov_primary_syms */
    nhsym ov_rogue_syms[SYM_MAX]; /* ov_rogue_syms */
    nhsym warnsyms[WARNCOUNT]; /* warnsyms */
    const char *known_handling[6]; /* known_handling */
    const char *known_restrictions[3]; /* known_restrictions */
    struct symparse loadsyms[186]; /* loadsyms */
    /* ---- src/dungeon.c ---- */
    int n_dgns; /* n_dgns */
    branch *s_dungeon_c_branches; /* static branches */
    mapseen *mapseenchn; /* mapseenchn */
    int l_dungeon_c_add_branch_branch_id; /* add_branch(): static branch_id */
    struct level_map level_map[27]; /* level_map */
    /* ---- src/eat.c ---- */
    char msgbuf[BUFSZ]; /* msgbuf */
    boolean s_eat_c_force_save_hs; /* static force_save_hs */
    const char *hu_stat[7]; /* hu_stat */
    char *s_eat_c_eatmbuf; /* static eatmbuf */
    long l_eat_c_maybe_cannibal_ate_brains; /* maybe_cannibal(): static ate_brains */
    unsigned int l_eat_c_newuhs_save_hs; /* newuhs(): static save_hs */
    boolean l_eat_c_newuhs_saved_hs; /* newuhs(): static saved_hs */
    /* ---- src/end.c ---- */
    struct valuable_data s_end_c_gems[23]; /* static gems */
    struct valuable_data s_end_c_amulets[11]; /* static amulets */
    struct val_list s_end_c_valuables[3]; /* static valuables */
    boolean l_end_c_NH_abort_aborting; /* NH_abort(): static aborting */
    boolean s_end_c_Schroedingers_cat; /* static Schroedingers_cat */
    int s_end_c_vanq_sortmode; /* static vanq_sortmode */
    /* ---- src/engrave.c ---- */
    struct engr *s_engrave_c_head_engr; /* static head_engr */
    /* ---- src/extralev.c ---- */
    struct rogueroom s_extralev_c_r[3][3]; /* static r */
    /* ---- src/files.c ---- */
    char s_files_c_fqn_filename_buffer[4][512]; /* static fqn_filename_buffer */
    char bones[12]; /* bones */
    char lock[PL_NSIZ+14]; /* lock */
    char SAVEF[45]; /* SAVEF */
    char s_files_c_wizkit[128]; /* static wizkit */
    char *s_files_c_config_section_chosen; /* static config_section_chosen */
    char *s_files_c_config_section_current; /* static config_section_current */
    char l_files_c_fname_encode_hexdigits[17]; /* fname_encode(): static hexdigits */
    char l_files_c_fname_decode_hexdigits[17]; /* fname_decode(): static hexdigits */
    int s_files_c_nesting; /* static nesting */
    int s_files_c_lockfd; /* static lockfd */
    struct flock sflock; /* sflock */
    const char *default_configfile; /* default_configfile */
    char configfile[BUFSZ]; /* configfile */
    struct _config_error_frame *s_files_c_config_error_data; /* static config_error_data */
    int s_files_c_symset_count; /* static symset_count */
    boolean s_files_c_chosen_symset_start; /* static chosen_symset_start */
    boolean s_files_c_chosen_symset_end; /* static chosen_symset_end */
    int s_files_c_symset_which_set; /* static symset_which_set */
    /* ---- src/hack.c ---- */
    anything s_hack_c_tmp_anything; /* static tmp_anything */
    long l_hack_c_moverock_lastmovetime; /* moverock(): static lastmovetime */
    int l_hack_c_domove_core_skates; /* domove_core(): static skates */
    int l_hack_c_spoteffects_inspoteffects; /* spoteffects(): static inspoteffects */
    coord l_hack_c_spoteffects_spotloc; /* spoteffects(): static spotloc */
    int l_hack_c_spoteffects_spotterrain; /* spoteffects(): static spotterrain */
    struct trap *l_hack_c_spoteffects_spottrap; /* spoteffects(): static spottrap */
    unsigned int l_hack_c_spoteffects_spottraptyp; /* spoteffects(): static spottraptyp */
    char l_hack_c_in_rooms_buf[5]; /* in_rooms(): static buf */
    int s_hack_c_wc; /* static wc */
    /* ---- src/hacklib.c ---- */
    char l_hacklib_c_s_suffix_buf[BUFSZ]; /* s_suffix(): static buf */
    char l_hacklib_c_ing_suffix_buf[BUFSZ]; /* ing_suffix(): static buf */
    char l_hacklib_c_visctrl_visctrl_bufs[5][5]; /* visctrl(): static visctrl_bufs */
    int l_hacklib_c_visctrl_nbuf; /* visctrl(): static nbuf */
    char l_hacklib_c_sitoa_buf[13]; /* sitoa(): static buf */
    unsigned long nle_seeds[2]; /* nle_seeds */
    char l_hacklib_c_yyyymmddhhmmss_datestr[15]; /* yyyymmddhhmmss(): static datestr */
    /* ---- src/invent.c ---- */
    int s_invent_c_lastinvnr; /* static lastinvnr */
    char s_invent_c_venom_inv[2]; /* static venom_inv */
    char l_invent_c_loot_classify_def_srt_order[MAXOCLASSES]; /* loot_classify(): static def_srt_order */
    char l_invent_c_loot_classify_armcat[8]; /* loot_classify(): static armcat */
    unsigned int s_invent_c_sortlootmode; /* static sortlootmode */
    struct xprnctx s_invent_c_safeq_xprn_ctx; /* static safeq_xprn_ctx */
    char l_invent_c_xprname_li[BUFSZ]; /* xprname(): static li */
    winid s_invent_c_cached_pickinv_win; /* static cached_pickinv_win */
    int s_invent_c_this_type; /* static this_type */
    char l_invent_c_dfeature_at_altbuf[BUFSZ]; /* dfeature_at(): static altbuf */
    char *s_invent_c_invbuf; /* static invbuf */
    unsigned int s_invent_c_invbufsiz; /* static invbufsiz */
    coord s_invent_c_only; /* static only */
    /* ---- src/light.c ---- */
    light_source *s_light_c_light_base; /* static light_base */
    /* ---- src/lock.c ---- */
    struct xlock_s s_lock_c_xlock; /* static xlock */
    char l_lock_c_pick_lock_no_longer[40]; /* pick_lock(): static no_longer */
    /* ---- src/makemon.c ---- */
    long l_makemon_c_align_shift_oldmoves; /* align_shift(): static oldmoves */
    s_level *l_makemon_c_align_shift_lev; /* align_shift(): static lev */
    struct nh_anon_s_makemon_c_rndmonst_state s_makemon_c_rndmonst_state; /* static rndmonst_state */
    /* ---- src/mapglyph.c ---- */
    char l_mapglyph_c_encglyph_encbuf[20]; /* encglyph(): static encbuf */
    /* ---- src/mhitm.c ---- */
    boolean s_mhitm_c_vis; /* static vis */
    boolean s_mhitm_c_far_noise; /* static far_noise */
    long s_mhitm_c_noisetime; /* static noisetime */
    struct obj *s_mhitm_c_otmp; /* static otmp */
    int s_mhitm_c_dieroll; /* static dieroll */
    /* ---- src/mhitu.c ---- */
    struct obj *s_mhitu_c_mon_currwep; /* static mon_currwep */
    int s_mhitu_c_dieroll; /* static dieroll */
    /* ---- src/mklev.c ---- */
    xchar s_mklev_c_vault_x; /* static vault_x */
    xchar s_mklev_c_vault_y; /* static vault_y */
    boolean s_mklev_c_made_branch; /* static made_branch */
    /* ---- src/mkmap.c ---- */
    char *s_mkmap_c_new_locations; /* static new_locations */
    int min_rx; /* min_rx */
    int max_rx; /* max_rx */
    int min_ry; /* min_ry */
    int max_ry; /* max_ry */
    int s_mkmap_c_n_loc_filled; /* static n_loc_filled */
    /* ---- src/mkmaze.c ---- */
    unsigned char s_mkmaze_c_bughack[24] __attribute__((aligned(8))); /* static bughack */
    struct bubble *s_mkmaze_c_bbubbles; /* static bbubbles */
    struct bubble *s_mkmaze_c_ebubbles; /* static ebubbles */
    struct trap *s_mkmaze_c_wportal; /* static wportal */
    int s_mkmaze_c_xmin; /* static xmin */
    int s_mkmaze_c_ymin; /* static ymin */
    int s_mkmaze_c_xmax; /* static xmax */
    int s_mkmaze_c_ymax; /* static ymax */
    boolean l_mkmaze_c_movebubbles_up; /* movebubbles(): static up */
    /* ---- src/mkobj.c ---- */
    char l_mkobj_c_where_name_unknown[32]; /* where_name(): static unknown */
    /* ---- src/mkroom.c ---- */
    coord l_mkroom_c_shrine_pos_buf; /* shrine_pos(): static buf */
    /* ---- src/mon.c ---- */
    boolean s_mon_c_vamp_rise_msg; /* static vamp_rise_msg */
    boolean s_mon_c_disintegested; /* static disintegested */
    long l_mon_c_elemental_clog_msgmv; /* elemental_clog(): static msgmv */
    short *s_mon_c_animal_list; /* static animal_list */
    int s_mon_c_animal_list_count; /* static animal_list_count */
    /* ---- src/monst.c ---- */
    struct permonst mons[382]; /* mons */
    /* ---- src/mthrowu.c ---- */
    int s_mthrowu_c_mesg_given; /* static mesg_given */
    struct monst *s_mthrowu_c_target; /* static target */
    struct monst *s_mthrowu_c_archer; /* static archer */
    /* ---- src/muse.c ---- */
    boolean m_using; /* m_using */
    struct musable s_muse_c_m; /* static m */
    int s_muse_c_trapx; /* static trapx */
    int s_muse_c_trapy; /* static trapy */
    boolean s_muse_c_zap_oseen; /* static zap_oseen */
    /* ---- src/music.c ---- */
    const char *beats[8]; /* beats */
    /* ---- src/o_init.c ---- */
    short s_o_init_c_disco[NUM_OBJECTS]; /* static disco */
    /* ---- src/objects.c ---- */
    struct objdescr obj_descr[454]; /* obj_descr */
    struct objclass objects[454]; /* objects */
    /* ---- src/objnam.c ---- */
    struct Jitem s_objnam_c_Japanese_items[13]; /* static Japanese_items */
    char s_objnam_c_obufs[12][256]; /* static obufs */
    int s_objnam_c_obufidx; /* static obufidx */
    int s_objnam_c_distantname; /* static distantname */
    struct sing_plur s_objnam_c_one_off[22]; /* static one_off */
    /* ---- src/options.c ---- */
    char s_options_c_empty_optstr[1]; /* static empty_optstr */
    struct Bool_Opt s_options_c_boolopt[87]; /* static boolopt */
    struct Comp_Opt s_options_c_compopt[80]; /* static compopt */
    boolean s_options_c_need_redraw; /* static need_redraw */
    char s_options_c_def_inv_order[MAXOCLASSES]; /* static def_inv_order */
    char mapped_menu_cmds[33]; /* mapped_menu_cmds */
    char s_options_c_mapped_menu_op[33]; /* static mapped_menu_op */
    short s_options_c_n_menu_mapped; /* static n_menu_mapped */
    boolean s_options_c_initial; /* static initial */
    boolean s_options_c_from_file; /* static from_file */
    char l_options_c_parseoptions_gpcoords[6]; /* parseoptions(): static gpcoords */
    char l_options_c_parseoptions_valid_settings[7]; /* parseoptions(): static valid_settings */
    char s_options_c_fmtstr_doset[16]; /* static fmtstr_doset */
    char s_options_c_fmtstr_doset_tab[8]; /* static fmtstr_doset_tab */
    char s_options_c_n_currently_set[19]; /* static n_currently_set */
    boolean l_options_c_doset_made_fmtstr; /* doset(): static made_fmtstr */
    struct symsetentry *symset_list; /* symset_list */
    const char *s_options_c_opt_intro[10]; /* static opt_intro */
    char *l_options_c_next_opt_buf; /* next_opt(): static buf */
    char **l_options_c_wc_set_window_colors_fgp[4]; /* wc_set_window_colors(): static fgp */
    char **l_options_c_wc_set_window_colors_bgp[4]; /* wc_set_window_colors(): static bgp */
    /* ---- src/pager.c ---- */
    char l_pager_c_do_screen_description_look_buf[BUFSZ]; /* do_screen_description(): static look_buf */
    const char *s_pager_c_suptext1[9]; /* static suptext1 */
    const char *s_pager_c_suptext2[7]; /* static suptext2 */
    boolean l_pager_c_dowhatdoes_once; /* dowhatdoes(): static once */
    /* ---- src/pickup.c ---- */
    struct obj *s_pickup_c_current_container; /* static current_container */
    boolean s_pickup_c_abort_looting; /* static abort_looting */
    long s_pickup_c_val_for_n_or_more; /* static val_for_n_or_more */
    char s_pickup_c_valid_menu_classes[MAXOCLASSES+1+4+1]; /* static valid_menu_classes */
    boolean s_pickup_c_class_filter; /* static class_filter */
    boolean s_pickup_c_bucx_filter; /* static bucx_filter */
    boolean s_pickup_c_shop_filter; /* static shop_filter */
    int l_pickup_c_add_valid_menu_class_vmc_count; /* add_valid_menu_class(): static vmc_count */
    boolean l_pickup_c_autopick_testobj_costly; /* autopick_testobj(): static costly */
    int l_pickup_c_encumber_msg_oldcap; /* encumber_msg(): static oldcap */
    /* ---- src/pline.c ---- */
    unsigned int s_pline_c_pline_flags; /* static pline_flags */
    char s_pline_c_prevmsg[BUFSZ]; /* static prevmsg */
    int l_pline_c_vpline_in_pline; /* vpline(): static in_pline */
    char *s_pline_c_you_buf; /* static you_buf */
    int s_pline_c_you_buf_siz; /* static you_buf_siz */
    /* ---- src/polyself.c ---- */
    int s_polyself_c_sex_change_ok; /* static sex_change_ok */
    /* ---- src/potion.c ---- */
    boolean notonhead; /* notonhead */
    int s_potion_c_nothing; /* static nothing */
    int s_potion_c_unkn; /* static unkn */
    const char *bottlenames[7]; /* bottlenames */
    /* ---- src/pray.c ---- */
    aligntyp s_pray_c_p_aligntyp; /* static p_aligntyp */
    int s_pray_c_p_trouble; /* static p_trouble */
    int s_pray_c_p_type; /* static p_type */
    /* ---- src/priest.c ---- */
    char l_priest_c_piousness_buf[32]; /* piousness(): static buf */
    /* ---- src/questpgr.c ---- */
    char s_questpgr_c_cvt_buf[64]; /* static cvt_buf */
    struct qtlists s_questpgr_c_qt_list; /* static qt_list */
    dlb *s_questpgr_c_msg_file; /* static msg_file */
    char s_questpgr_c_nambuf[64]; /* static nambuf */
    /* ---- src/read.c ---- */
    boolean known; /* known */
    struct litmon *s_read_c_gremlins; /* static gremlins */
    /* ---- src/rect.c ---- */
    NhRect s_rect_c_rect[51]; /* static rect */
    int s_rect_c_rect_cnt; /* static rect_cnt */
    /* ---- src/region.c ---- */
    NhRegion **s_region_c_regions; /* static regions */
    int s_region_c_n_regions; /* static n_regions */
    int s_region_c_max_regions; /* static max_regions */
    /* ---- src/restore.c ---- */
    struct restore_procs s_restore_c_restoreprocs; /* static restoreprocs */
    int s_restore_c_n_ids_mapped; /* static n_ids_mapped */
    struct bucket *s_restore_c_id_map; /* static id_map */
    boolean restoring; /* restoring */
    struct fruit *s_restore_c_oldfruit; /* static oldfruit */
    long s_restore_c_omoves; /* static omoves */
    /* ---- src/rip.c ---- */
    char **s_rip_c_rip; /* static rip */
    /* ---- src/rnd.c ---- */
    struct rnglist_t s_rnd_c_rnglist[2]; /* static rnglist */
    /* ---- src/role.c ---- */
    struct Role urole; /* urole */
    struct Race urace; /* urace */
    unsigned char s_role_c_rfilter[16] __attribute__((aligned(2))); /* static rfilter */
    char s_role_c_randomstr[7]; /* static randomstr */
    char s_role_c_pa[4]; /* static pa */
    char s_role_c_post_attribs; /* static post_attribs */
    char l_role_c_root_plselection_prompt_err_ret[13]; /* root_plselection_prompt(): static err_ret */
    /* ---- src/rumors.c ---- */
    long s_rumors_c_true_rumor_size; /* static true_rumor_size */
    long s_rumors_c_false_rumor_size; /* static false_rumor_size */
    unsigned long s_rumors_c_true_rumor_start; /* static true_rumor_start */
    unsigned long s_rumors_c_false_rumor_start; /* static false_rumor_start */
    long s_rumors_c_true_rumor_end; /* static true_rumor_end */
    long s_rumors_c_false_rumor_end; /* static false_rumor_end */
    int s_rumors_c_oracle_flg; /* static oracle_flg */
    unsigned int s_rumors_c_oracle_cnt; /* static oracle_cnt */
    unsigned long *s_rumors_c_oracle_loc; /* static oracle_loc */
    /* ---- src/save.c ---- */
    struct save_procs s_save_c_saveprocs; /* static saveprocs */
    unsigned int s_save_c_ustuck_id; /* static ustuck_id */
    unsigned int s_save_c_usteed_id; /* static usteed_id */
    int s_save_c_bw_fd; /* static bw_fd */
    FILE *s_save_c_bw_FILE; /* static bw_FILE */
    boolean s_save_c_buffering; /* static buffering */
    struct trap l_save_c_savetrapchn_zerotrap; /* savetrapchn(): static zerotrap */
    struct fruit l_save_c_savefruitchn_zerofruit; /* savefruitchn(): static zerofruit */
    /* ---- src/shk.c ---- */
    long s_shk_c_followmsg; /* static followmsg */
    char l_shk_c_u_entered_shop_empty_shops[5]; /* u_entered_shop(): static empty_shops */
    long l_shk_c_pick_pick_pickmovetime; /* pick_pick(): static pickmovetime */
    struct repo s_shk_c_repo; /* static repo */
    char s_shk_c_sell_response; /* static sell_response */
    int s_shk_c_sell_how; /* static sell_how */
    boolean s_shk_c_auto_credit; /* static auto_credit */
    const char *Izchak_speaks[9]; /* Izchak_speaks */
    /* ---- src/sp_lev.c ---- */
    char s_sp_lev_c_SpLev_Map[COLNO][ROWNO]; /* static SpLev_Map */
    aligntyp s_sp_lev_c_ralign[3]; /* static ralign */
    xchar s_sp_lev_c_xstart; /* static xstart */
    xchar s_sp_lev_c_ystart; /* static ystart */
    char s_sp_lev_c_xsize; /* static xsize */
    char s_sp_lev_c_ysize; /* static ysize */
    char *lev_message; /* lev_message */
    unsigned char lregions[8] __attribute__((aligned(8))); /* lregions */
    int num_lregions; /* num_lregions */
    boolean s_sp_lev_c_splev_init_present; /* static splev_init_present */
    boolean s_sp_lev_c_icedpools; /* static icedpools */
    int s_sp_lev_c_mines_prize_count; /* static mines_prize_count */
    int s_sp_lev_c_soko_prize_count; /* static soko_prize_count */
    struct obj *s_sp_lev_c_container_obj[10]; /* static container_obj */
    int s_sp_lev_c_container_idx; /* static container_idx */
    struct monst *s_sp_lev_c_invent_carrying_monster; /* static invent_carrying_monster */
    unsigned char l_sp_lev_c_get_unpacked_coord_c[24] __attribute__((aligned(8))); /* get_unpacked_coord(): static c */
    int (*s_sp_lev_c_selection_flood_check_func)(int, int); /* static selection_flood_check_func */
    schar s_sp_lev_c_floodfillchk_match_under_typ; /* static floodfillchk_match_under_typ */
    /* ---- src/spell.c ---- */
    struct tport_hideaway l_spell_c_tport_spell_save_tport; /* tport_spell(): static save_tport */
    int s_spell_c_spl_sortmode; /* static spl_sortmode */
    int *s_spell_c_spl_orderindx; /* static spl_orderindx */
    /* ---- src/steal.c ---- */
    unsigned int stealoid; /* stealoid */
    unsigned int stealmid; /* stealmid */
    /* ---- src/sys.c ---- */
    struct sysopt sysopt; /* sysopt */
    /* ---- src/teleport.c ---- */
    struct obj *s_teleport_c_telescroll; /* static telescroll */
    /* ---- src/timeout.c ---- */
    timer_element *s_timeout_c_timer_base; /* static timer_base */
    unsigned long s_timeout_c_timer_id; /* static timer_id */
    /* ---- src/topten.c ---- */
    struct toptenentry *tt_head; /* tt_head */
    winid s_topten_c_toptenwin; /* static toptenwin */
    struct toptenentry l_topten_c_get_rnd_toptenentry_tt_buf; /* get_rnd_toptenentry(): static tt_buf */
    /* ---- src/track.c ---- */
    int s_track_c_utcnt; /* static utcnt */
    int s_track_c_utpnt; /* static utpnt */
    coord s_track_c_utrack[50]; /* static utrack */
    /* ---- src/trap.c ---- */
    int s_trap_c_force_mintrap; /* static force_mintrap */
    boolean l_trap_c_dotrap_recursive_mine; /* dotrap(): static recursive_mine */
    char l_trap_c_trapnote_tnbuf[12]; /* trapnote(): static tnbuf */
    struct nh_anon_s_trap_c_launchplace s_trap_c_launchplace; /* static launchplace */
    struct h2o_ctx s_trap_c_acid_ctx; /* static acid_ctx */
    /* ---- src/u_init.c ---- */
    struct trobj s_u_init_c_Archeologist[9]; /* static Archeologist */
    struct trobj s_u_init_c_Barbarian[5]; /* static Barbarian */
    struct trobj s_u_init_c_Cave_man[6]; /* static Cave_man */
    struct trobj s_u_init_c_Healer[11]; /* static Healer */
    struct trobj s_u_init_c_Knight[9]; /* static Knight */
    struct trobj s_u_init_c_Monk[10]; /* static Monk */
    struct trobj s_u_init_c_Priest[8]; /* static Priest */
    struct trobj s_u_init_c_Ranger[7]; /* static Ranger */
    struct trobj s_u_init_c_Rogue[7]; /* static Rogue */
    struct trobj s_u_init_c_Samurai[6]; /* static Samurai */
    struct trobj s_u_init_c_Tourist[8]; /* static Tourist */
    struct trobj s_u_init_c_Valkyrie[5]; /* static Valkyrie */
    struct trobj s_u_init_c_Wizard[9]; /* static Wizard */
    struct trobj s_u_init_c_Tinopener[2]; /* static Tinopener */
    struct trobj s_u_init_c_Magicmarker[2]; /* static Magicmarker */
    struct trobj s_u_init_c_Lamp[2]; /* static Lamp */
    struct trobj s_u_init_c_Blindfold[2]; /* static Blindfold */
    struct trobj s_u_init_c_Instrument[2]; /* static Instrument */
    struct trobj s_u_init_c_Xtra_food[2]; /* static Xtra_food */
    struct trobj s_u_init_c_Leash[2]; /* static Leash */
    struct trobj s_u_init_c_Towel[2]; /* static Towel */
    struct trobj s_u_init_c_Wishing[2]; /* static Wishing */
    struct trobj s_u_init_c_Money[2]; /* static Money */
    short l_u_init_c_ini_inv_nocreate; /* ini_inv(): static nocreate */
    short l_u_init_c_ini_inv_nocreate2; /* ini_inv(): static nocreate2 */
    short l_u_init_c_ini_inv_nocreate3; /* ini_inv(): static nocreate3 */
    short l_u_init_c_ini_inv_nocreate4; /* ini_inv(): static nocreate4 */
    /* ---- src/uhitm.c ---- */
    boolean s_uhitm_c_override_confirmation; /* static override_confirmation */
    boolean l_uhitm_c_hitum_cleave_clockwise; /* hitum_cleave(): static clockwise */
    char l_uhitm_c_gulpum_msgbuf[BUFSZ]; /* gulpum(): static msgbuf */
    /* ---- src/vision.c ---- */
    char circle_data[136]; /* circle_data */
    char circle_start[16]; /* circle_start */
    char *viz_rmin; /* viz_rmin */
    char *viz_rmax; /* viz_rmax */
    char s_vision_c_could_see[2][ROWNO][COLNO]; /* static could_see */
    char *s_vision_c_cs_rows0[ROWNO]; /* static cs_rows0 */
    char *s_vision_c_cs_rows1[ROWNO]; /* static cs_rows1 */
    char s_vision_c_cs_rmin0[ROWNO]; /* static cs_rmin0 */
    char s_vision_c_cs_rmax0[ROWNO]; /* static cs_rmax0 */
    char s_vision_c_cs_rmin1[ROWNO]; /* static cs_rmin1 */
    char s_vision_c_cs_rmax1[ROWNO]; /* static cs_rmax1 */
    char s_vision_c_viz_clear[ROWNO][COLNO]; /* static viz_clear */
    char *s_vision_c_viz_clear_rows[ROWNO]; /* static viz_clear_rows */
    char s_vision_c_left_ptrs[ROWNO][COLNO]; /* static left_ptrs */
    char s_vision_c_right_ptrs[ROWNO][COLNO]; /* static right_ptrs */
    unsigned char l_vision_c_vision_recalc_colbump[COLNO+1]; /* vision_recalc(): static colbump */
    int s_vision_c_start_row; /* static start_row */
    int s_vision_c_start_col; /* static start_col */
    int s_vision_c_step; /* static step */
    char **s_vision_c_cs_rows; /* static cs_rows */
    char *s_vision_c_cs_left; /* static cs_left */
    char *s_vision_c_cs_right; /* static cs_right */
    void (*s_vision_c_vis_func)(int, int, genericptr_t); /* static vis_func */
    genericptr_t s_vision_c_varg; /* static varg */
    /* ---- src/weapon.c ---- */
    struct obj *s_weapon_c_propellor; /* static propellor */
    /* ---- src/windows.c ---- */
    volatile struct window_procs windowprocs; /* windowprocs */
    struct win_choices s_windows_c_winchoices[3]; /* static winchoices */
    struct win_choices *s_windows_c_last_winchoice; /* static last_winchoice */
    void (*s_windows_c_previnterface_exit_nhwindows)(const char *); /* static previnterface_exit_nhwindows */
    const char *status_fieldnm[MAXBLSTATS]; /* status_fieldnm */
    const char *status_fieldfmt[MAXBLSTATS]; /* status_fieldfmt */
    char *status_vals[MAXBLSTATS]; /* status_vals */
    boolean status_activefields[MAXBLSTATS]; /* status_activefields */
    enum statusfields l_windows_c_genl_status_update_fieldorder[5][15]; /* genl_status_update(): static fieldorder */
    FILE *s_windows_c_dumplog_file; /* static dumplog_file */
    /* ---- src/worm.c ---- */
    struct wseg *wheads[MAX_NUM_WORMS]; /* wheads */
    struct wseg *wtails[MAX_NUM_WORMS]; /* wtails */
    long wgrowtime[MAX_NUM_WORMS]; /* wgrowtime */
    /* ---- src/worn.c ---- */
    struct worn worn[17]; /* worn */
    /* ---- src/zap.c ---- */
    boolean s_zap_c_obj_zapped; /* static obj_zapped */
    int s_zap_c_poly_zapped; /* static poly_zapped */
    /* ---- sys/share/ioctl.c ---- */
    struct termios termio; /* termio */
    /* ---- sys/share/posixregex.c ---- */
    char l_posixregex_c_regex_error_desc_buf[BUFSZ]; /* regex_error_desc(): static buf */
    /* ---- sys/unix/unixmain.c ---- */
    boolean s_unixmain_c_wiz_error_flag; /* static wiz_error_flag */
    struct passwd *l_unixmain_c_get_unix_pw_pw; /* get_unix_pw(): static pw */
    char l_unixmain_c_get_login_name_buf[BUFSZ]; /* get_login_name(): static buf */
    /* ---- win/tty/getline.c ---- */
    char morc; /* morc */
    boolean s_getline_c_suppress_history; /* static suppress_history */
    boolean xwaitingforspace; /* xwaitingforspace */
    /* ---- win/tty/termcap.c ---- */
    struct tc_lcl_data tc_lcl_data; /* tc_lcl_data */
    char *s_termcap_c_HO; /* static HO */
    char *s_termcap_c_CL; /* static CL */
    char *s_termcap_c_CE; /* static CE */
    char *s_termcap_c_UP; /* static UP */
    char *s_termcap_c_XD; /* static XD */
    char *s_termcap_c_BC; /* static BC */
    char *s_termcap_c_SO; /* static SO */
    char *s_termcap_c_SE; /* static SE */
    char *s_termcap_c_TI; /* static TI */
    char *s_termcap_c_TE; /* static TE */
    char *s_termcap_c_VS; /* static VS */
    char *s_termcap_c_VE; /* static VE */
    char *s_termcap_c_ME; /* static ME */
    char *s_termcap_c_MR; /* static MR */
    char *s_termcap_c_MB; /* static MB */
    char *s_termcap_c_MH; /* static MH */
    char *s_termcap_c_MD; /* static MD */
    char *hilites[CLR_MAX]; /* hilites */
    char s_termcap_c_nullstr[1]; /* static nullstr */
    char s_termcap_c_tgotobuf[20]; /* static tgotobuf */
    char s_termcap_c_adef_nilstring[1]; /* static adef_nilstring */
    char s_termcap_c_nulstr[1]; /* static nulstr */
    /* ---- win/tty/topl.c ---- */
    char **s_topl_c_snapshot_mesgs; /* static snapshot_mesgs */
    int l_topl_c_tty_getmsghistory_nxtidx; /* tty_getmsghistory(): static nxtidx */
    boolean l_topl_c_tty_putmsghistory_initd; /* tty_putmsghistory(): static initd */
    /* ---- win/tty/wintty.c ---- */
    struct window_procs tty_procs; /* tty_procs */
    winid BASE_WINDOW; /* BASE_WINDOW */
    struct WinDesc *wins[20]; /* wins */
    struct DisplayDesc *ttyDisplay; /* ttyDisplay */
    char s_wintty_c_winpanicstr[17]; /* static winpanicstr */
    char defmorestr[9]; /* defmorestr */
    char l_wintty_c_compress_str_cbuf[BUFSZ]; /* compress_str(): static cbuf */
    volatile int l_wintty_c_tty_nhgetch_nesting; /* tty_nhgetch(): static nesting */
    unsigned long *s_wintty_c_tty_colormasks; /* static tty_colormasks */
    long s_wintty_c_tty_condition_bits; /* static tty_condition_bits */
    unsigned char s_wintty_c_tty_status[1840] __attribute__((aligned(8))); /* static tty_status */
    int s_wintty_c_hpbar_percent; /* static hpbar_percent */
    int s_wintty_c_hpbar_color; /* static hpbar_color */
    const enum statusfields (*s_wintty_c_fieldorder)[15]; /* static fieldorder */
    int s_wintty_c_finalx[3][2]; /* static finalx */
    boolean s_wintty_c_windowdata_init; /* static windowdata_init */
    int s_wintty_c_cond_shrinklvl; /* static cond_shrinklvl */
    int s_wintty_c_enclev; /* static enclev */
    int s_wintty_c_enc_shrinklvl; /* static enc_shrinklvl */
    int s_wintty_c_dlvl_shrinklvl; /* static dlvl_shrinklvl */
    boolean s_wintty_c_truncation_expected; /* static truncation_expected */
    boolean l_wintty_c_status_sanity_check_in_sanity_check; /* status_sanity_check(): static in_sanity_check */
    unsigned int l_wintty_c_render_status_once_only; /* render_status(): static once_only */
};

#ifndef NH_THREAD_LOCAL
#define NH_THREAD_LOCAL __thread
#endif
extern NH_THREAD_LOCAL struct nh_globals *nh_g;

/* Zero a context and re-apply every static initializer (the .data image
 * of the original globals). Sets `nh_g` to it. */
void nh_globals_init(struct nh_globals *);
size_t nh_globals_size(void);
/* per-file initializer copies (generated at the end of each file; weak so
 * that programs linking a subset of the game can skip them) */
void nh_init_artifact_c(void) __attribute__((weak));
void nh_init_attrib_c(void) __attribute__((weak));
void nh_init_cmd_c(void) __attribute__((weak));
void nh_init_decl_c(void) __attribute__((weak));
void nh_init_detect_c(void) __attribute__((weak));
void nh_init_dungeon_c(void) __attribute__((weak));
void nh_init_end_c(void) __attribute__((weak));
void nh_init_mkmaze_c(void) __attribute__((weak));
void nh_init_options_c(void) __attribute__((weak));
void nh_init_windows_c(void) __attribute__((weak));
void nh_init_worn_c(void) __attribute__((weak));

/* --- accessor macros for the objects that kept their names ------------ */
#define ARGV0 (nh_g->ARGV0)
#define BASE_WINDOW (nh_g->BASE_WINDOW)
#define Cmd (nh_g->Cmd)
#define Izchak_speaks (nh_g->Izchak_speaks)
#define SAVEF (nh_g->SAVEF)
#define WIN_INVEN (nh_g->WIN_INVEN)
#define WIN_MAP (nh_g->WIN_MAP)
#define WIN_MESSAGE (nh_g->WIN_MESSAGE)
#define WIN_STATUS (nh_g->WIN_STATUS)
#define afternmv (nh_g->afternmv)
#define apelist (nh_g->apelist)
#define bases (nh_g->bases)
#define beats (nh_g->beats)
#define bhitpos (nh_g->bhitpos)
#define billobjs (nh_g->billobjs)
#define bottlenames (nh_g->bottlenames)
#define c_obj_colors (nh_g->c_obj_colors)
#define catname (nh_g->catname)
#define chosen_windowtype (nh_g->chosen_windowtype)
#define circle_data (nh_g->circle_data)
#define circle_start (nh_g->circle_start)
#define configfile (nh_g->configfile)
#define context (nh_g->context)
#define current_wand (nh_g->current_wand)
#define currentgraphics (nh_g->currentgraphics)
#define default_configfile (nh_g->default_configfile)
#define defer_see_monsters (nh_g->defer_see_monsters)
#define defmorestr (nh_g->defmorestr)
#define dndest (nh_g->dndest)
#define dnladder (nh_g->dnladder)
#define dnstair (nh_g->dnstair)
#define dnstairs_room (nh_g->dnstairs_room)
#define dogname (nh_g->dogname)
#define domove_attempting (nh_g->domove_attempting)
#define domove_succeeded (nh_g->domove_succeeded)
#define done_money (nh_g->done_money)
#define doorindex (nh_g->doorindex)
#define doors (nh_g->doors)
#define dungeon_topology (nh_g->dungeon_topology)
#define dungeons (nh_g->dungeons)
#define extcmdlist (nh_g->extcmdlist)
#define extcmdlist_length (nh_g->extcmdlist_length)
#define ffruit (nh_g->ffruit)
#define fqn_prefix (nh_g->fqn_prefix)
#define fqn_prefix_names (nh_g->fqn_prefix_names)
#define ftrap (nh_g->ftrap)
#define hackpid (nh_g->hackpid)
#define has_strong_rngseed (nh_g->has_strong_rngseed)
#define hilites (nh_g->hilites)
#define hname (nh_g->hname)
#define horsename (nh_g->horsename)
#define hu_stat (nh_g->hu_stat)
#define iflags (nh_g->iflags)
#define in_doagain (nh_g->in_doagain)
#define in_mklev (nh_g->in_mklev)
#define in_steed_dismounting (nh_g->in_steed_dismounting)
#define inv_pos (nh_g->inv_pos)
#define invent (nh_g->invent)
#define kickedobj (nh_g->kickedobj)
#define known_handling (nh_g->known_handling)
#define known_restrictions (nh_g->known_restrictions)
#define lastseentyp (nh_g->lastseentyp)
#define lev_message (nh_g->lev_message)
#define level_info (nh_g->level_info)
#define loadsyms (nh_g->loadsyms)
#define lock (nh_g->lock)
#define locknum (nh_g->locknum)
#define lregions (*(lev_region * *) nh_g->lregions)
#define m_shot (nh_g->m_shot)
#define m_using (nh_g->m_using)
#define mapped_menu_cmds (nh_g->mapped_menu_cmds)
#define mapseenchn (nh_g->mapseenchn)
#define materialnm (nh_g->materialnm)
#define max_rx (nh_g->max_rx)
#define max_ry (nh_g->max_ry)
#define menu_colorings (nh_g->menu_colorings)
#define migrating_mons (nh_g->migrating_mons)
#define migrating_objs (nh_g->migrating_objs)
#define min_rx (nh_g->min_rx)
#define min_ry (nh_g->min_ry)
#define mons (nh_g->mons)
#define monstermoves (nh_g->monstermoves)
#define morc (nh_g->morc)
#define moves (nh_g->moves)
#define mrg_to_wielded (nh_g->mrg_to_wielded)
#define multi (nh_g->multi)
#define multi_reason (nh_g->multi_reason)
#define mydogs (nh_g->mydogs)
#define n_dgns (nh_g->n_dgns)
#define nhUse_dummy (nh_g->nhUse_dummy)
#define nle_seeds (nh_g->nle_seeds)
#define nomovemsg (nh_g->nomovemsg)
#define notonhead (nh_g->notonhead)
#define nsubroom (nh_g->nsubroom)
#define num_lregions (nh_g->num_lregions)
#define obj_descr (nh_g->obj_descr)
#define occtime (nh_g->occtime)
#define occtxt (nh_g->occtxt)
#define occupation (nh_g->occupation)
#define otg_temp (nh_g->otg_temp)
#define ov_primary_syms (nh_g->ov_primary_syms)
#define ov_rogue_syms (nh_g->ov_rogue_syms)
#define pl_character (nh_g->pl_character)
#define pl_fruit (nh_g->pl_fruit)
#define pl_race (nh_g->pl_race)
#define plinemsg_types (nh_g->plinemsg_types)
#define plname (nh_g->plname)
#define preferred_pet (nh_g->preferred_pet)
#define primary_syms (nh_g->primary_syms)
#define quest_status (nh_g->quest_status)
#define ransacked (nh_g->ransacked)
#define restoring (nh_g->restoring)
#define rogue_syms (nh_g->rogue_syms)
#define rooms (nh_g->rooms)
#define save_cm (nh_g->save_cm)
#define save_dlevel (nh_g->save_dlevel)
#define seenv_matrix (nh_g->seenv_matrix)
#define sfcap (nh_g->sfcap)
#define sflock (nh_g->sflock)
#define sfrestinfo (nh_g->sfrestinfo)
#define sfsaveinfo (nh_g->sfsaveinfo)
#define showsyms (nh_g->showsyms)
#define smeq (nh_g->smeq)
#define sp_levchn (nh_g->sp_levchn)
#define spl_book (nh_g->spl_book)
#define sstairs (nh_g->sstairs)
#define sstairs_room (nh_g->sstairs_room)
#define status_activefields (nh_g->status_activefields)
#define status_fieldfmt (nh_g->status_fieldfmt)
#define status_fieldnm (nh_g->status_fieldnm)
#define status_hilites (nh_g->status_hilites)
#define status_vals (nh_g->status_vals)
#define stealmid (nh_g->stealmid)
#define stoned (nh_g->stoned)
#define subrooms (nh_g->subrooms)
#define symset (nh_g->symset)
#define symset_list (nh_g->symset_list)
#define tbx (nh_g->tbx)
#define tby (nh_g->tby)
#define thrownobj (nh_g->thrownobj)
#define toplines (nh_g->toplines)
#define tt_head (nh_g->tt_head)
#define ttyDisplay (nh_g->ttyDisplay)
#define tty_procs (nh_g->tty_procs)
#define tune (nh_g->tune)
#define u (nh_g->u)
#define uamul (nh_g->uamul)
#define uarm (nh_g->uarm)
#define uarmc (nh_g->uarmc)
#define uarmf (nh_g->uarmf)
#define uarmg (nh_g->uarmg)
#define uarmh (nh_g->uarmh)
#define uarms (nh_g->uarms)
#define uarmu (nh_g->uarmu)
#define uball (nh_g->uball)
#define ubirthday (nh_g->ubirthday)
#define ublindf (nh_g->ublindf)
#define uchain (nh_g->uchain)
#define uleft (nh_g->uleft)
#define unweapon (nh_g->unweapon)
#define updest (nh_g->updest)
#define upladder (nh_g->upladder)
#define upstair (nh_g->upstair)
#define upstairs_room (nh_g->upstairs_room)
#define uquiver (nh_g->uquiver)
#define urace (nh_g->urace)
#define urealtime (nh_g->urealtime)
#define uright (nh_g->uright)
#define urole (nh_g->urole)
#define uskin (nh_g->uskin)
#define uswapwep (nh_g->uswapwep)
#define uwep (nh_g->uwep)
#define vision_full_recalc (nh_g->vision_full_recalc)
#define viz_array (nh_g->viz_array)
#define viz_rmax (nh_g->viz_rmax)
#define viz_rmin (nh_g->viz_rmin)
#define wailmsg (nh_g->wailmsg)
#define warn_obj_cnt (nh_g->warn_obj_cnt)
#define warnsyms (nh_g->warnsyms)
#define wgrowtime (nh_g->wgrowtime)
#define wheads (nh_g->wheads)
#define windowprocs (nh_g->windowprocs)
#define wins (nh_g->wins)
#define wtails (nh_g->wtails)
#define x_maze_max (nh_g->x_maze_max)
#define xwaitingforspace (nh_g->xwaitingforspace)
#define y_maze_max (nh_g->y_maze_max)
#define yn_number (nh_g->yn_number)
#define youmonst (nh_g->youmonst)

#endif /* NH_GLOBALS_H */
