#ifndef NLE_H
#define NLE_H

#define NLE_BZ2_TTYRECS

#include <stdio.h>
#include <stddef.h>

#include <fcontext/fcontext.h>

#include "nleobs.h"

/* This header is included both by the game (hack.h TUs) and by files that
 * see only config.h (alloc.c, also built into the utilities), so it must
 * not depend on hack.h: the game state is reached through an opaque
 * pointer. */
struct nh_globals;
struct isaac64_ctx;

/* ---------------------------------------------------------------------------
 * nle_tune_t — parametric difficulty knobs.
 *
 * The knob catalog is defined ONCE via the X-macro below; the struct, the
 * defaults, and the name table are all generated from it, and the binding
 * treats nle_tune_t as a flat array of doubles indexed by the name table.
 * Adding a knob = add one X() line here + read it at one engine decision
 * site; no get/set plumbing changes anywhere (binding or C).
 *
 * Every knob is a double so the generic get/set works uniformly: floats are
 * scales (1.0 = vanilla), bools are 0.0/1.0, ints are truncated. A scale knob
 * that should be "off"/"use vanilla" uses the documented sentinel in its
 * read-site (e.g. vision_radius <= 0 means "vanilla").
 *
 * X(name, default)
 */
#define NLE_TUNE_FIELDS(X)                 \
    X(dmg_to_player_scale,      1.0)       \
    X(dmg_by_player_scale,      1.0)       \
    X(player_hp_scale,          1.0)       \
    X(hp_regen_scale,           1.0)       \
    X(vision_radius,            0.0)       \
    X(reveal_map,               0.0)       \
    X(hunger_rate_scale,        1.0)       \
    X(ongoing_spawn_scale,      1.0)       \
    X(monster_difficulty_scale, 1.0)       \
    X(monster_speed_scale,      1.0)       \
    X(xp_gain_scale,            1.0)       \
    X(room_density,             1.0)       \
    X(mob_spawn,                1.0)       \
    X(trap_density,             1.0)       \
    X(locked_door,              1.0)       \
    X(corridor_connectivity,    1.0)       \
    X(room_size,                1.0)

typedef struct nle_tune {
#define NLE_TUNE_DECL(name, dflt) double name;
    NLE_TUNE_FIELDS(NLE_TUNE_DECL)
#undef NLE_TUNE_DECL
} nle_tune_t;

/* Convenience accessor for engine read-sites: `nle_tuning.<knob>`. Resolves to
 * the current env's knob block (current_nle_ctx is anchored on every step). */
#define nle_tuning (current_nle_ctx->knobs)

/* TODO: Fix this. */
#undef SIG_RET_TYPE
#define SIG_RET_TYPE void (*)(int)

typedef struct TMT TMT;

/* One environment. Everything the game itself mutates lives in `*g`
 * (struct nh_globals, generated by tools/collect_globals); this struct is
 * the NLE layer's own per-environment state around it. A context and its
 * globals are one contiguous block (see nle_ctx_block_size), so a snapshot
 * of an environment is a memcpy of the block plus the arena, the coroutine
 * stack and the rl display mirror. */
typedef struct nle_ctx {
    /* game coroutine */
    fcontext_stack_t stack;
    fcontext_t returncontext;
    fcontext_t generatorcontext;

    /* terminal / recording */
    FILE *ttyrec;
    TMT *vterminal;
    char outbuf[BUFSIZ];
    char *outbuf_write_ptr;
    char *outbuf_write_end;
#ifdef NLE_BZ2_TTYRECS
    void *ttyrec_bz2;
#endif

    int done;
    nle_obs *observation;

    /* per-env configuration (used to be file statics in nle.c) */
    nle_settings settings;
    nle_seeds_init_t *seeds_init;
    nle_tune_t knobs;

    /* per-env bump arena: every alloc() the game makes lands here, free()
     * is a no-op, so the heap state is captured by copying [base, used). */
    char *arena_base;
    size_t arena_used;
    size_t arena_cap;

    /* rl window port (win/rl/winrl.cc): the NetHackRL instance and the
     * win-proc trace deque, both libc-allocated (outside the arena). */
    void *rl_instance;
    void *rl_win_proc_calls;
    int rl_in_yn_function;
    int rl_in_getlin;

    void *sentinel; /* nle_sentinel slot for this env (may be NULL) */

    /* the game's globals; points just past this struct in the same block */
    struct nh_globals *g;
} nle_ctx_t;

/* THE per-env context pointer: thread-local so every stepping thread chases
 * its own environment. Re-anchored (together with nh_g) at every public
 * entry point by nle_anchor(). initial-exec TLS is a plain fs-relative
 * load; the loader reserves static TLS for a dlopen'd library that asks
 * for it (DT_FLAGS_1 STATIC_TLS), which is how the Python binding loads
 * libnethack. */
extern __attribute__((tls_model("initial-exec")))
       __thread nle_ctx_t *current_nle_ctx;

void nle_anchor(nle_ctx_t *);
size_t nle_ctx_block_size(void);

nle_ctx_t *nle_start(nle_obs *, FILE *, nle_seeds_init_t *, nle_settings *);
nle_ctx_t *nle_step(nle_ctx_t *, nle_obs *);
void nle_end(nle_ctx_t *);

void nle_set_seed(nle_ctx_t *, unsigned long, unsigned long, boolean);
void nle_get_seed(nle_ctx_t *, unsigned long *, unsigned long *, boolean *);

/* Debug: dump the per-env memory map (regions, fmon/fobj chains, monster
 * grid with fmon-membership) to `path` (NULL => stderr). */
/* ttyrec continuity across a snapshot/restore (see nle.c). */
long nle_ttyrec_mark(nle_ctx_t *);
void nle_ttyrec_rewind(nle_ctx_t *, long);

void nle_dbg_memmap(nle_ctx_t *, const char *);

/* Single-level blob save/load.
 *
 * nle_save_level serializes the current dungeon level to a malloc'd byte
 * blob (length written to *out_len); the caller owns it and must release
 * it with nle_free_blob. nle_load_level stamps a previously saved blob over
 * the current level and reloads its contents in place.
 *
 * NOTE: nle_load_level is two-phase. It mutates engine state and resets
 * vision but does NOT re-render the map (re-rendering routes through the
 * window port, which yields the game coroutine and is unsafe from this
 * entry point). The caller must step the game once to render. */
void *nle_save_level(nle_ctx_t *, long *out_len);
void  nle_free_blob(void *blob);
int   nle_load_level(nle_ctx_t *, const void *blob, long len);

/* Hero (player) state blob save/load (save.c / restore.c).
 *
 * nle_save_player serializes the full hero gamestate -- the `u` struct,
 * inventory, attributes, killers/timers/light-sources and the dungeon graph
 * (everything dosave0()'s gamestate tail writes), WITHOUT the level map --
 * to a malloc'd byte blob (length written to *out_len). The live game is left
 * intact (WRITE_SAVE, not FREE_SAVE). Caller owns the blob; free it with
 * nle_free_blob. Pairs with nle_save_level: a checkpoint = level blob +
 * player blob. Returns the blob, or NULL on error.
 *
 * nle_load_player restores such a blob onto the CURRENT level. Returns 0 on
 * success, nonzero on error.
 *
 * LOAD ORDERING CONTRACT: call nle_load_level BEFORE nle_load_player. The
 * player restore relinks u.ustuck / u.usteed and the worn ball/chain against
 * the current level's monster/object chains, so the target level must already
 * be installed. Two-phase like nle_load_level: the caller steps once. */
void *nle_save_player(nle_ctx_t *, long *out_len);
int   nle_load_player(nle_ctx_t *, const void *blob, long len);

/* Secure state-modification API.
 *
 * nle_set_state pokes a curated whitelist of simple integer player fields.
 * "field" is one of: "hp", "max_hp", "gold", "xp_level", "hunger", "luck",
 * or one of the six attributes "str"/"dex"/"con"/"int"/"wis"/"cha" (value is
 * NetHack's encoded attribute: 3..18, 19..118 == 18/01..18/00, 119..125 ==
 * 19..25). Returns 0 on success, nonzero for an unknown field. The C side
 * only provides the setters; the binding is responsible for validating
 * bounds.
 *
 * nle_goto_depth schedules a DEFERRED move of the hero to dungeon level n
 * in the current dungeon branch: it sets u.utolev / u.utotype so the game
 * loop performs the change via deferred_goto() on the next nle_step().
 * Returns 0 on success, nonzero on bad target. */
int nle_set_state(nle_ctx_t *, const char *field, long value);
int nle_goto_depth(nle_ctx_t *, int n);

/* nle_seat_on_stair seats the hero on the down (down != 0) or up staircase of
 * the current level, if present. Two-phase like goto_depth. Returns 0 on
 * success, nonzero if no such stair exists.
 *
 * nle_level_up raises the hero n experience levels with the normal HP/stat
 * gains (pluslvl), capped at level 30, and bumps u.uexp to the new level
 * threshold so the next newexplevel() won't undo it. Returns 0 on success. */
int nle_seat_on_stair(nle_ctx_t *, int down);
int nle_level_up(nle_ctx_t *, int n);

/* Curriculum traversal: cross-branch goto + dungeon-table query.
 *
 * nle_num_dungeons returns the number of dungeon branches defined.
 * nle_dungeon_info reports branch `idx`'s name / depth_start / num_dunlevs
 * (any out pointer may be NULL).
 * nle_goto_abs schedules a DEFERRED move to an arbitrary (dnum, dlevel),
 * including a different branch than the hero's current one. Reaching the
 * Elemental Planes grants the Amulet (the goto_level gate). All return 0 on
 * success, nonzero on a bad index / out-of-range target. */
int nle_num_dungeons(nle_ctx_t *);
int nle_dungeon_info(nle_ctx_t *, int idx, char *name_out, int name_cap,
                     int *depth_start_out, int *num_dunlevs_out);
int nle_goto_abs(nle_ctx_t *, int dnum, int dlevel);
/* nle_hero_on_stair: +1 on the down stair, -1 on the up stair, +-2 on the
 * branch staircase, 0 otherwise. */
int nle_hero_on_stair(nle_ctx_t *);

/* nle_grant_invocation_kit: drop the pre-primed invocation artifacts (lit
 * spe=7 Candelabrum, charged Bell of Opening, Book of the Dead -- all uncursed)
 * straight into the hero's pack. Returns 0.
 * nle_invocation_pos: write the vibrating-square coords into *x,*y; returns 0
 * on the Invocation level (coords valid), nonzero otherwise (x,y set 0).
 * nle_seat_on_invocation_square: stage the hero at the vibrating square;
 * adjacent!=0 places the hero next to it. Returns 0 on success. */
int nle_grant_invocation_kit(nle_ctx_t *);
int nle_invocation_pos(nle_ctx_t *, int *x, int *y);
int nle_seat_on_invocation_square(nle_ctx_t *, int adjacent);

/* Per-env RNG state (rnd.c). CORE = 0 (gameplay RNG), DISP = 1 (display). */
struct isaac64_ctx *nle_rng_state(int idx);

/* Both RNG contexts (CORE, DISP) as one blob, for the portable checkpoint.
 * The in-memory snapshot carries them inside the per-env block already; the
 * on-disk checkpoint stores NetHack's save blobs, which never held the RNG. */
size_t nle_rng_blob_size(void);
void nle_rng_save(void *);
void nle_rng_load(const void *);
boolean            *nle_rng_init_flag(int idx);

/* Arena-backed calloc (alloc.c). Per-env state allocated through this lands
 * in the per-env arena and is captured by nle_fr_snapshot. */
void *nle_arena_calloc(size_t count, size_t size);

/* Difficulty knob catalog (nle.c). The binding calls count()/name() once to
 * learn the catalog, then reads/writes nle_get_tune(nle) as a flat double[]. */
int          nle_tune_count(void);
const char  *nle_tune_name(int index);
void         nle_tune_set_defaults(nle_tune_t *t);
nle_tune_t  *nle_get_tune(nle_ctx_t *nle);

/* Fast-reset snapshot (nle_fast_reset.c). The handle is a LIVE-PROCESS
 * construct -- a coroutine-stack image, arena bytes addressed off
 * nle->arena_base, and the rl display mirror -- so it can NEVER be written
 * to disk; a cross-process checkpoint is (nle_save_player + nle_save_level +
 * nle_fr_levelfiles_blob) instead. */
void *nle_fr_snapshot(nle_ctx_t *nle);
void  nle_fr_restore(nle_ctx_t *nle, void *snap);
void  nle_fr_destroy(void *snap);

/* Level-file integrity. goto_level (do.c) kills the hero with done(TRICKED)
 * when level_info[].flags says a level file exists and it does not, so
 * these exist to make that divergence detectable instead of fatal:
 *   nle_fr_last_restore_rc  0 iff the last restore rewrote the whole set
 *   nle_fr_levelfile_count  how many files a snapshot handle bundled
 *   nle_fr_missing_levelfiles  ledgers flagged EXISTS with no file on disk */
int nle_fr_last_restore_rc(void);
int nle_fr_levelfile_count(void *snap);
int nle_fr_missing_levelfiles(nle_ctx_t *nle);

/* Portable level-file set, for disk checkpoints. The blob is malloc'd; free it
 * with nle_free_blob. nle_save_player serializes level_info[] (save_dungeon),
 * so a resumed game believes in every level the original visited -- these files
 * MUST travel with the checkpoint or the first stair use fakes a death. */
void *nle_fr_levelfiles_blob(nle_ctx_t *nle, long *out_len);
int   nle_fr_levelfiles_load(nle_ctx_t *nle, const void *blob, long len);

#endif /* NLE_H */
